/**
 * AURA Module Registry
 * Central registry for all system modules with versioning and dependencies
 */

export const AURA_MODULES = {
  // Core Modules (Existing - DO NOT MODIFY)
  STAFF: {
    id: 'staff',
    version: '1.0.0',
    status: 'stable',
    entities: ['User', 'TeamMember', 'Shift', 'Availability'],
    pages: ['Staff', 'StaffRota', 'MyShifts'],
    protected: true,
  },
  INVENTORY: {
    id: 'inventory',
    version: '1.0.0',
    status: 'stable',
    entities: ['Ingredient', 'Supplier', 'PurchaseOrder'],
    pages: ['Inventory', 'SupplierManagement', 'Ordering'],
    protected: true,
  },
  TASKS: {
    id: 'tasks',
    version: '1.0.0',
    status: 'stable',
    entities: ['StaffTask', 'AutoGeneratedTask'],
    pages: ['MyTasks', 'TaskReports'],
    protected: true,
  },
  CHECKLISTS: {
    id: 'checklists',
    version: '1.0.0',
    status: 'stable',
    entities: ['ChecklistTemplate', 'ChecklistExecution'],
    pages: ['MyChecklists', 'ExecuteChecklist'],
    protected: true,
  },
  FORMS: {
    id: 'forms',
    version: '1.0.0',
    status: 'stable',
    entities: ['FormTemplate', 'FormResponse', 'FormAssignmentMetadata'],
    pages: ['FormIntelligence', 'FormBuilder'],
    protected: true,
  },

  // Phase 2 Modules (NEW)
  SOPCORE: {
    id: 'sopcore',
    version: '2.0.0',
    status: 'active',
    entities: ['SOPDocument', 'SOPVersion', 'SOPSignatureLog', 'SOPCertification', 'MenuSOPLink'],
    pages: ['SOPDashboard', 'SOPBuilder', 'SOPViewer', 'SOPCertifications'],
    dependencies: ['STAFF', 'MENU'],
    protected: false,
  },
  QUALITYCORE: {
    id: 'qualitycore',
    version: '2.0.0',
    status: 'active',
    entities: ['QualityRecord', 'QualityTemplate', 'QualityScore'],
    pages: ['QualityDashboard', 'QuickQualityCheck', 'QualityTemplates', 'QualityReports'],
    dependencies: ['STAFF', 'SOPCORE'],
    protected: false,
  },
  AIAGENTS: {
    id: 'aiagents',
    version: '2.0.0',
    status: 'beta',
    entities: ['AgentLog', 'AgentAction', 'AgentInsight'],
    pages: ['AIConsole', 'AgentMonitor'],
    dependencies: ['STAFF', 'INVENTORY', 'QUALITYCORE'],
    protected: false,
  },
  HYGIENE: {
    id: 'hygiene',
    version: '2.0.0',
    status: 'active',
    entities: ['HygieneRecord', 'HygieneUserScore', 'HygieneAlertLog'],
    pages: ['HygieneDashboard'],
    dependencies: ['STAFF', 'FORMS'],
    protected: false,
  },
  AUDIT: {
    id: 'audit',
    version: '2.0.0',
    status: 'active',
    entities: ['AuditCheckpoint', 'AuditExecution'],
    pages: ['EHOControlCenter'],
    dependencies: ['COMPLIANCE', 'HYGIENE', 'QUALITYCORE'],
    protected: false,
  },
};

export const MODULE_STATUS = {
  STABLE: 'stable',
  ACTIVE: 'active',
  BETA: 'beta',
  DEPRECATED: 'deprecated',
};

export function getModuleInfo(moduleId) {
  return AURA_MODULES[moduleId.toUpperCase()];
}

export function getModuleDependencies(moduleId) {
  const module = getModuleInfo(moduleId);
  return module?.dependencies?.map(dep => AURA_MODULES[dep]) || [];
}

export function isModuleProtected(moduleId) {
  const module = getModuleInfo(moduleId);
  return module?.protected === true;
}

export function getActiveModules() {
  return Object.values(AURA_MODULES).filter(m => 
    m.status === MODULE_STATUS.STABLE || m.status === MODULE_STATUS.ACTIVE
  );
}