import { base44 } from '@/api/base44Client';

/**
 * 🔗 Shift Auto-Linker
 * Automatically attaches tasks and SOPs when creating shifts
 * 
 * Logic:
 * 1. Based on role/position, find relevant SOPs
 * 2. Based on shift_type (opening/mid/closing), find relevant tasks
 * 3. Auto-create StaffTask records linked to the shift
 * 4. Auto-link SOPs via shift metadata
 */

export async function autoLinkTasksAndSOPs(shift) {
  try {
    const { role, shift_type, staff_email, staff_name, shift_date, id: shiftId } = shift;

    // ========================================
    // 1️⃣ FIND RELEVANT SOPs
    // ========================================
    const allSOPs = await base44.entities.SOPDocument.list();
    const relevantSOPs = allSOPs.filter(sop => 
      sop.role_assigned?.includes(role.toLowerCase()) || 
      sop.role_assigned?.includes('all')
    );

    console.log(`[AutoLinker] Found ${relevantSOPs.length} relevant SOPs for ${role}`);

    // ========================================
    // 2️⃣ FIND RELEVANT TASKS FROM ROLE RESPONSIBILITIES
    // ========================================
    const roleResponsibilities = await base44.entities.RoleResponsibility.filter({
      position: role.toLowerCase(),
    });

    let tasksToCreate = [];

    if (roleResponsibilities.length > 0) {
      const roleResp = roleResponsibilities[0];
      
      // Get tasks based on shift type
      if (shift_type === 'opening' && roleResp.daily_tasks) {
        tasksToCreate = roleResp.daily_tasks
          .filter(t => typeof t === 'object' && t.task_name)
          .map(t => ({
            task_name: t.task_name,
            description: t.description || '',
            priority: t.priority || 'medium',
            estimated_minutes: t.estimated_minutes || 30,
          }));
      }
    }

    // ========================================
    // 3️⃣ CREATE AUTO-GENERATED TASKS
    // ========================================
    const createdTasks = [];
    for (const task of tasksToCreate) {
      try {
        const newTask = await base44.entities.AutoGeneratedTask.create({
          task_name: task.task_name,
          description: task.description,
          assigned_to_email: staff_email,
          assigned_to_name: staff_name,
          role: role,
          shift_id: shiftId,
          shift_date: shift_date,
          priority: task.priority,
          estimated_minutes: task.estimated_minutes,
          status: 'pending',
          created_automatically: true,
          task_type: 'daily',
        });
        createdTasks.push(newTask);
      } catch (error) {
        console.error(`[AutoLinker] Failed to create task: ${task.task_name}`, error);
      }
    }

    console.log(`[AutoLinker] ✅ Created ${createdTasks.length} auto-tasks for shift ${shiftId}`);

    // ========================================
    // 4️⃣ UPDATE SHIFT WITH LINKED SOPs
    // ========================================
    if (relevantSOPs.length > 0) {
      await base44.entities.Shift.update(shiftId, {
        ...shift,
        auto_generated_tasks: true,
        tasks_generated_at: new Date().toISOString(),
        notes: `${shift.notes || ''}\n\n📚 SOPs: ${relevantSOPs.map(s => s.title).join(', ')}`.trim(),
      });
    }

    return {
      tasksCreated: createdTasks.length,
      sopsLinked: relevantSOPs.length,
      sopsList: relevantSOPs.map(s => ({ id: s.id, title: s.title })),
    };

  } catch (error) {
    console.error('[AutoLinker] Error in autoLinkTasksAndSOPs:', error);
    return {
      tasksCreated: 0,
      sopsLinked: 0,
      sopsList: [],
    };
  }
}

/**
 * Get all linked tasks and SOPs for a shift
 */
export async function getShiftLinkedResources(shiftId) {
  try {
    const [tasks, shift] = await Promise.all([
      base44.entities.AutoGeneratedTask.filter({ shift_id: shiftId }),
      base44.entities.Shift.filter({ id: shiftId }),
    ]);

    // Extract SOP IDs from shift notes (if any)
    const sopIds = shift[0]?.notes?.match(/📚 SOPs: (.+)/)?.[1]?.split(', ') || [];

    return {
      tasks: tasks || [],
      sopTitles: sopIds,
    };
  } catch (error) {
    console.error('[AutoLinker] Error getting linked resources:', error);
    return { tasks: [], sopTitles: [] };
  }
}