import { useState } from "react";
import { base44 } from "@/api/base44Client";
import { useQuery } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import {
  Search,
  FileDown,
  ArrowLeft,
  ShieldAlert,
  Eye,
  FileSpreadsheet,
  FileText,
  AlertTriangle,
  CheckCircle,
  Info
} from "lucide-react";
import { Link } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { format } from "date-fns";
import { motion, AnimatePresence } from "framer-motion";

// Allergen icons
const allergenIcons = {
  milk: "🥛",
  nuts: "🥜",
  gluten: "🌾",
  soy: "🌱",
  egg: "🥚",
  fish: "🐟",
  shellfish: "🦐",
  sesame: "◉",
  celery: "🥬",
  mustard: "🌼",
  sulphites: "🍷",
  lupin: "🫘"
};

const riskColors = {
  none: "bg-emerald-100 text-emerald-800 border-emerald-300",
  low: "bg-blue-100 text-blue-800 border-blue-300",
  medium: "bg-amber-100 text-amber-800 border-amber-300",
  high: "bg-red-100 text-red-800 border-red-300"
};

export default function AllergyTable() {
  const [searchQuery, setSearchQuery] = useState("");
  const [filterCategory, setFilterCategory] = useState("all");
  const [filterRisk, setFilterRisk] = useState("all");
  const [selectedRecord, setSelectedRecord] = useState(null);
  const [showDetailModal, setShowDetailModal] = useState(false);

  const { data: user } = useQuery({
    queryKey: ['currentUser'],
    queryFn: () => base44.auth.me(),
  });

  const { data: allergyRecords = [], isLoading } = useQuery({
    queryKey: ['allergyRecords'],
    queryFn: () => base44.entities.AllergyRecord.list('-last_synced'),
  });

  const { data: categories = [] } = useQuery({
    queryKey: ['menuCategories'],
    queryFn: () => base44.entities.MenuCategory.list(),
  });

  const { data: suppliers = [] } = useQuery({
    queryKey: ['suppliers'],
    queryFn: () => base44.entities.Supplier.list(),
  });

  const handleExportCSV = () => {
    const headers = ['Item Name', 'Category', 'Allergens', 'Risk Level', 'Last Updated'];
    const rows = filteredRecords.map(record => [
      record.menu_item_name,
      record.category,
      record.allergens_detected.join(', '),
      record.risk_level,
      record.last_synced ? format(new Date(record.last_synced), 'dd/MM/yyyy HH:mm') : 'Never'
    ]);

    const csvContent = [
      headers.join(','),
      ...rows.map(row => row.join(','))
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `allergy-table-${format(new Date(), 'yyyy-MM-dd')}.csv`;
    a.click();
    alert('✅ CSV exported successfully!');
  };

  const handleExportPDF = async () => {
    const content = `
AURA ONE PRO - ALLERGY INFORMATION TABLE
Generated: ${format(new Date(), 'dd MMMM yyyy HH:mm')}
Generated by: ${user?.full_name} (${user?.email})
===============================================

${filteredRecords.map(record => `
${record.menu_item_name} (${record.category})
Allergens: ${record.allergens_detected.map(a => `${allergenIcons[a]} ${a}`).join(', ') || 'None detected'}
Risk Level: ${record.risk_level.toUpperCase()}
Last Synced: ${record.last_synced ? format(new Date(record.last_synced), 'dd/MM/yyyy HH:mm') : 'Never'}

Ingredient Sources:
${record.ingredient_sources?.map(src => `  - ${src.ingredient_name}: ${src.allergens.map(a => `${allergenIcons[a]} ${a}`).join(', ')}`).join('\n') || '  No ingredient data'}
---
`).join('\n')}

===============================================
This document is auto-generated and reflects current menu allergen information.
For compliance purposes, verify with kitchen staff before service.

Compliance Officer Signature: _________________________
Date: _____________________________
Verification Stamp: _______________________________
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `allergy-table-${format(new Date(), 'yyyy-MM-dd')}.txt`;
    a.click();

    alert('✅ Allergy table exported! For PDF format, please print this file to PDF.');
  };

  const handleViewDetails = (record) => {
    setSelectedRecord(record);
    setShowDetailModal(true);
  };

  // Filter records
  const filteredRecords = allergyRecords.filter(record => {
    const matchesSearch = record.menu_item_name.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesCategory = filterCategory === "all" || record.category === filterCategory;
    const matchesRisk = filterRisk === "all" || record.risk_level === filterRisk;
    
    return matchesSearch && matchesCategory && matchesRisk;
  });

  // Sort by risk level (high first)
  const sortedRecords = [...filteredRecords].sort((a, b) => {
    const riskOrder = { high: 0, medium: 1, low: 2, none: 3 };
    return riskOrder[a.risk_level] - riskOrder[b.risk_level];
  });

  return (
    <div className="p-6 md:p-8 bg-gradient-to-br from-slate-50 to-slate-100 min-h-screen">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="flex justify-between items-start mb-8">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <div className="p-3 bg-gradient-to-br from-amber-500 to-amber-600 rounded-xl">
                <ShieldAlert className="w-8 h-8 text-white" />
              </div>
              <div>
                <h1 className="text-4xl font-bold text-gray-900" style={{ fontFamily: 'Poppins, Inter, sans-serif' }}>
                  Allergy Information Table ⚠️
                </h1>
                <p className="text-gray-600 text-lg">Auto-generated allergen tracking for menu compliance</p>
              </div>
            </div>
          </div>
          <div className="flex gap-3">
            <Link to={createPageUrl("Menu")}>
              <Button variant="outline" size="sm" className="border-emerald-600 text-emerald-700 hover:bg-emerald-50">
                <ArrowLeft className="w-4 h-4 mr-2" />
                Back to Menu
              </Button>
            </Link>
            <Button variant="outline" size="sm" onClick={handleExportCSV} className="border-blue-600 text-blue-700 hover:bg-blue-50">
              <FileSpreadsheet className="w-4 h-4 mr-2" />
              Export CSV
            </Button>
            <Button variant="outline" size="sm" onClick={handleExportPDF} className="border-purple-600 text-purple-700 hover:bg-purple-50">
              <FileText className="w-4 h-4 mr-2" />
              Export PDF
            </Button>
          </div>
        </div>

        {/* Info Banner */}
        <Card className="mb-6 border-amber-200 bg-amber-50">
          <CardContent className="p-4">
            <div className="flex items-start gap-3">
              <Info className="w-5 h-5 text-amber-600 mt-0.5" />
              <div>
                <p className="font-semibold text-amber-900">Automatic Allergen Tracking</p>
                <p className="text-sm text-amber-800 mt-1">
                  This table is automatically updated when menu items or ingredients change. All data is timestamped and audit-logged for compliance.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Stats */}
        <div className="grid md:grid-cols-4 gap-4 mb-6">
          <Card className="bg-gradient-to-br from-gray-700 to-gray-800 text-white border-none shadow-lg">
            <CardContent className="p-4">
              <div className="text-2xl font-bold">{allergyRecords.length}</div>
              <div className="text-sm text-gray-300">Total Items</div>
            </CardContent>
          </Card>
          <Card className="bg-gradient-to-br from-red-500 to-red-600 text-white border-none shadow-lg">
            <CardContent className="p-4">
              <div className="text-2xl font-bold">
                {allergyRecords.filter(r => r.risk_level === 'high').length}
              </div>
              <div className="text-sm text-red-100">High Risk</div>
            </CardContent>
          </Card>
          <Card className="bg-gradient-to-br from-amber-500 to-amber-600 text-white border-none shadow-lg">
            <CardContent className="p-4">
              <div className="text-2xl font-bold">
                {allergyRecords.filter(r => r.risk_level === 'medium').length}
              </div>
              <div className="text-sm text-amber-100">Medium Risk</div>
            </CardContent>
          </Card>
          <Card className="bg-gradient-to-br from-emerald-500 to-emerald-600 text-white border-none shadow-lg">
            <CardContent className="p-4">
              <div className="text-2xl font-bold">
                {allergyRecords.filter(r => r.allergens_detected.length === 0).length}
              </div>
              <div className="text-sm text-emerald-100">Allergen Free</div>
            </CardContent>
          </Card>
        </div>

        {/* Filters */}
        <Card className="bg-white border-none shadow-sm mb-6">
          <CardContent className="p-4">
            <div className="flex flex-wrap gap-4">
              <div className="flex-1 min-w-[200px]">
                <div className="relative">
                  <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-4 h-4" />
                  <Input
                    placeholder="Search items..."
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    className="pl-10 border-gray-300 focus:border-emerald-500 focus:ring-emerald-500"
                  />
                </div>
              </div>
              <Select value={filterCategory} onValueChange={setFilterCategory}>
                <SelectTrigger className="w-48 border-gray-300">
                  <SelectValue placeholder="All Categories" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Categories</SelectItem>
                  {categories.map(cat => (
                    <SelectItem key={cat.id} value={cat.name}>{cat.name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
              <Select value={filterRisk} onValueChange={setFilterRisk}>
                <SelectTrigger className="w-48 border-gray-300">
                  <SelectValue placeholder="Risk Level" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Risk Levels</SelectItem>
                  <SelectItem value="high">🔴 High Risk</SelectItem>
                  <SelectItem value="medium">🟡 Medium Risk</SelectItem>
                  <SelectItem value="low">🔵 Low Risk</SelectItem>
                  <SelectItem value="none">🟢 No Allergens</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </CardContent>
        </Card>

        {/* Table */}
        <Card className="bg-white border-none shadow-lg">
          <CardContent className="p-0">
            {isLoading ? (
              <div className="text-center py-12">
                <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-amber-600 mx-auto"></div>
                <p className="mt-4 text-gray-600">Loading allergy data...</p>
              </div>
            ) : sortedRecords.length === 0 ? (
              <div className="text-center py-12">
                <AlertTriangle className="w-16 h-16 text-gray-300 mx-auto mb-4" />
                <p className="text-gray-500">No allergy records found</p>
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead className="bg-gradient-to-r from-emerald-50 to-amber-50 border-b-2 border-emerald-200">
                    <tr>
                      <th className="text-left p-4 font-bold text-gray-800" style={{ fontFamily: 'Poppins, sans-serif' }}>
                        Item Name
                      </th>
                      <th className="text-left p-4 font-bold text-gray-800">Category</th>
                      <th className="text-left p-4 font-bold text-gray-800">Allergens</th>
                      <th className="text-left p-4 font-bold text-gray-800">Risk Level</th>
                      <th className="text-left p-4 font-bold text-gray-800">Last Updated</th>
                      <th className="text-left p-4 font-bold text-gray-800">Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    <AnimatePresence>
                      {sortedRecords.map((record, index) => (
                        <motion.tr
                          key={record.id}
                          initial={{ opacity: 0, x: -20 }}
                          animate={{ opacity: 1, x: 0 }}
                          exit={{ opacity: 0, x: 20 }}
                          transition={{ delay: index * 0.03 }}
                          className={`border-b hover:bg-gray-50 transition-colors ${
                            index % 2 === 0 ? 'bg-white' : 'bg-gray-50/50'
                          }`}
                        >
                          <td className="p-4">
                            <div className="font-semibold text-gray-900">{record.menu_item_name}</div>
                          </td>
                          <td className="p-4">
                            <Badge variant="outline" className="border-emerald-300 text-emerald-800 bg-emerald-50">
                              {record.category}
                            </Badge>
                          </td>
                          <td className="p-4">
                            {record.allergens_detected.length > 0 ? (
                              <div className="flex flex-wrap gap-1.5">
                                {record.allergens_detected.map(allergen => (
                                  <Badge 
                                    key={allergen} 
                                    variant="outline" 
                                    className="text-xs border-amber-300 text-amber-900 bg-amber-50"
                                  >
                                    {allergenIcons[allergen]} {allergen}
                                  </Badge>
                                ))}
                              </div>
                            ) : (
                              <span className="text-gray-400 text-sm flex items-center gap-1">
                                <CheckCircle className="w-4 h-4 text-emerald-500" />
                                None detected
                              </span>
                            )}
                          </td>
                          <td className="p-4">
                            <Badge className={`${riskColors[record.risk_level]} border font-semibold`}>
                              {record.risk_level.toUpperCase()}
                            </Badge>
                          </td>
                          <td className="p-4 text-sm text-gray-600">
                            {record.last_synced ? format(new Date(record.last_synced), 'dd/MM/yyyy HH:mm') : 'Never'}
                          </td>
                          <td className="p-4">
                            <Button
                              variant="outline"
                              size="sm"
                              onClick={() => handleViewDetails(record)}
                              className="border-blue-600 text-blue-700 hover:bg-blue-50"
                            >
                              <Eye className="w-4 h-4 mr-1" />
                              Details
                            </Button>
                          </td>
                        </motion.tr>
                      ))}
                    </AnimatePresence>
                  </tbody>
                </table>
              </div>
            )}
          </CardContent>
        </Card>

        {/* Detail Modal */}
        <Dialog open={showDetailModal} onOpenChange={setShowDetailModal}>
          <DialogContent className="max-w-2xl">
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2 text-2xl" style={{ fontFamily: 'Poppins, sans-serif' }}>
                <ShieldAlert className="w-6 h-6 text-amber-600" />
                Allergen Details: {selectedRecord?.menu_item_name}
              </DialogTitle>
            </DialogHeader>

            {selectedRecord && (
              <div className="space-y-6 mt-4">
                <div>
                  <h3 className="font-bold text-gray-900 mb-2" style={{ fontFamily: 'Poppins, sans-serif' }}>
                    Category
                  </h3>
                  <Badge variant="outline" className="border-emerald-300 text-emerald-800 bg-emerald-50">
                    {selectedRecord.category}
                  </Badge>
                </div>

                <div>
                  <h3 className="font-bold text-gray-900 mb-2">Risk Level</h3>
                  <Badge className={`${riskColors[selectedRecord.risk_level]} border text-lg px-4 py-2`}>
                    {selectedRecord.risk_level.toUpperCase()}
                  </Badge>
                </div>

                <div>
                  <h3 className="font-bold text-gray-900 mb-2">Allergens Detected</h3>
                  {selectedRecord.allergens_detected.length > 0 ? (
                    <div className="flex flex-wrap gap-2">
                      {selectedRecord.allergens_detected.map(allergen => (
                        <Badge 
                          key={allergen} 
                          variant="outline" 
                          className="text-base py-2 px-3 border-amber-300 text-amber-900 bg-amber-50"
                          style={{ borderColor: '#E0B037' }}
                        >
                          {allergenIcons[allergen]} {allergen}
                        </Badge>
                      ))}
                    </div>
                  ) : (
                    <p className="text-gray-500 flex items-center gap-2">
                      <CheckCircle className="w-5 h-5 text-emerald-500" />
                      No allergens detected
                    </p>
                  )}
                </div>

                {selectedRecord.ingredient_sources && selectedRecord.ingredient_sources.length > 0 && (
                  <div>
                    <h3 className="font-bold text-gray-900 mb-3">Ingredient Sources</h3>
                    <div className="space-y-2">
                      {selectedRecord.ingredient_sources.map((source, index) => {
                        const supplier = suppliers.find(s => 
                          s.id === suppliers.find(sup => sup.name === source.supplier_name)?.id
                        );

                        return (
                          <div key={index} className="p-3 bg-gray-50 rounded-lg border border-gray-200">
                            <p className="font-semibold text-gray-900">{source.ingredient_name}</p>
                            <p className="text-sm text-amber-800 mt-1">
                              Contains: {source.allergens.map(a => `${allergenIcons[a]} ${a}`).join(', ')}
                            </p>
                            {supplier && (
                              <p className="text-xs text-gray-500 mt-1">
                                Supplier: {supplier.name} • {supplier.email}
                              </p>
                            )}
                          </div>
                        );
                      })}
                    </div>
                  </div>
                )}

                <div>
                  <h3 className="font-bold text-gray-900 mb-2">Last Synced</h3>
                  <p className="text-gray-600">
                    {selectedRecord.last_synced ? format(new Date(selectedRecord.last_synced), 'PPpp') : 'Never'}
                  </p>
                </div>

                {selectedRecord.auto_generated && (
                  <div className="p-3 bg-blue-50 rounded-lg border border-blue-200">
                    <p className="text-sm text-blue-800">
                      ℹ️ This record was automatically generated from ingredient data and synced with the menu system.
                    </p>
                  </div>
                )}

                {selectedRecord.verified_by && (
                  <div className="p-3 bg-emerald-50 rounded-lg border border-emerald-200">
                    <p className="text-sm text-emerald-800">
                      ✅ Verified by: {selectedRecord.verified_by} on {format(new Date(selectedRecord.verified_at), 'PPpp')}
                    </p>
                  </div>
                )}
              </div>
            )}
          </DialogContent>
        </Dialog>
      </div>
    </div>
  );
}