import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Textarea } from "@/components/ui/textarea";
import { CheckCircle, Clock, AlertCircle, Camera, FileText, ArrowLeft, Home, PlayCircle, X } from "lucide-react";
import { format } from "date-fns";
import { Link } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { motion } from "framer-motion";

export default function MyTasks() {
  const queryClient = useQueryClient();
  const [selectedTask, setSelectedTask] = useState(null);
  const [uploading, setUploading] = useState(false);
  const [taskNotes, setTaskNotes] = useState("");

  const { data: user } = useQuery({
    queryKey: ['currentUser'],
    queryFn: () => base44.auth.me(),
  });

  const today = new Date().toISOString().split('T')[0];

  const { data: myTasks = [], isLoading } = useQuery({
    queryKey: ['myTasks', user?.email, today],
    queryFn: () => base44.entities.AutoGeneratedTask.filter({
      assigned_to_email: user?.email,
      shift_date: today
    }),
    enabled: !!user?.email,
  });

  const updateTaskMutation = useMutation({
    mutationFn: ({ id, data }) => base44.entities.AutoGeneratedTask.update(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['myTasks'] });
      setSelectedTask(null);
      setTaskNotes("");
    },
  });

  const handleStartTask = async (task) => {
    await updateTaskMutation.mutateAsync({
      id: task.id,
      data: {
        status: 'in_progress',
        started_at: new Date().toISOString(),
      }
    });
  };

  const handleCompleteTask = async (task) => {
    if (task.requires_photo && !task.photo_url) {
      alert('Photo evidence is required for this task');
      return;
    }

    await updateTaskMutation.mutateAsync({
      id: task.id,
      data: {
        status: 'completed',
        completed_at: new Date().toISOString(),
        notes: taskNotes,
      }
    });
  };

  const handlePhotoUpload = async (e, task) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setUploading(true);
    try {
      const { file_url } = await base44.integrations.Core.UploadFile({ file });
      await updateTaskMutation.mutateAsync({
        id: task.id,
        data: { photo_url: file_url }
      });
    } catch (error) {
      console.error('Error uploading photo:', error);
      alert('Failed to upload photo');
    }
    setUploading(false);
  };

  const pendingTasks = myTasks.filter(t => t.status === 'pending');
  const inProgressTasks = myTasks.filter(t => t.status === 'in_progress');
  const completedTasks = myTasks.filter(t => t.status === 'completed');
  const totalTasks = myTasks.length;
  const progress = totalTasks > 0 ? Math.round((completedTasks.length / totalTasks) * 100) : 0;

  const getPriorityColor = (priority) => {
    switch (priority) {
      case 'high': return 'bg-red-100 text-red-800 border-red-200';
      case 'medium': return 'bg-yellow-100 text-yellow-800 border-yellow-200';
      case 'low': return 'bg-green-100 text-green-800 border-green-200';
      default: return 'bg-gray-100 text-gray-800 border-gray-200';
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 p-6 md:p-8">
      <div className="max-w-5xl mx-auto">
        {/* Back Buttons */}
        <div className="flex gap-3 mb-6">
          <Link to={createPageUrl("Dashboard")}>
            <Button variant="outline" size="sm">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back
            </Button>
          </Link>
          <Link to={createPageUrl("Dashboard")}>
            <Button variant="outline" size="sm">
              <Home className="w-4 h-4 mr-2" />
              Dashboard
            </Button>
          </Link>
        </div>

        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
        >
          <Card className="bg-gradient-to-r from-blue-600 to-indigo-600 text-white border-none shadow-lg mb-6">
            <CardContent className="p-8">
              <h1 className="text-3xl font-bold mb-2">
                👋 Hello {user?.full_name?.split(' ')[0]}, here are your tasks for today
              </h1>
              <p className="text-blue-100 mb-4">{format(new Date(), 'EEEE, MMMM d, yyyy')}</p>
              
              <div className="bg-white/20 rounded-lg p-4 backdrop-blur-sm">
                <div className="flex justify-between text-sm mb-2">
                  <span>Overall Progress</span>
                  <span className="font-bold">{progress}% Complete</span>
                </div>
                <Progress value={progress} className="h-3 bg-white/30" />
                <div className="flex justify-between text-xs mt-2">
                  <span>{completedTasks.length} / {totalTasks} tasks completed</span>
                  <span>{pendingTasks.length + inProgressTasks.length} remaining</span>
                </div>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Quick Stats */}
        <div className="grid grid-cols-3 gap-4 mb-6">
          <Card>
            <CardContent className="p-4 text-center">
              <Clock className="w-6 h-6 text-yellow-600 mx-auto mb-2" />
              <p className="text-2xl font-bold text-gray-900">{pendingTasks.length}</p>
              <p className="text-sm text-gray-600">Pending</p>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-4 text-center">
              <PlayCircle className="w-6 h-6 text-blue-600 mx-auto mb-2" />
              <p className="text-2xl font-bold text-gray-900">{inProgressTasks.length}</p>
              <p className="text-sm text-gray-600">In Progress</p>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-4 text-center">
              <CheckCircle className="w-6 h-6 text-green-600 mx-auto mb-2" />
              <p className="text-2xl font-bold text-gray-900">{completedTasks.length}</p>
              <p className="text-sm text-gray-600">Completed</p>
            </CardContent>
          </Card>
        </div>

        {/* Tasks List */}
        {isLoading ? (
          <Card>
            <CardContent className="p-6">
              <div className="animate-pulse space-y-3">
                {[1, 2, 3].map(i => (
                  <div key={i} className="h-20 bg-gray-200 rounded" />
                ))}
              </div>
            </CardContent>
          </Card>
        ) : myTasks.length === 0 ? (
          <Card>
            <CardContent className="p-12 text-center">
              <CheckCircle className="w-16 h-16 text-green-600 mx-auto mb-4" />
              <h3 className="text-xl font-bold text-gray-900 mb-2">All Done! 🎉</h3>
              <p className="text-gray-600">You don't have any tasks assigned for today</p>
            </CardContent>
          </Card>
        ) : (
          <div className="space-y-4">
            {myTasks
              .sort((a, b) => {
                // Sort by status (pending/in_progress first, then completed)
                const statusOrder = { pending: 1, in_progress: 2, completed: 3 };
                const statusDiff = (statusOrder[a.status] || 4) - (statusOrder[b.status] || 4);
                if (statusDiff !== 0) return statusDiff;
                
                // Then sort by priority
                const priorityOrder = { high: 1, medium: 2, low: 3 };
                return (priorityOrder[a.priority] || 4) - (priorityOrder[b.priority] || 4);
              })
              .map((task, index) => (
                <motion.div
                  key={task.id}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: index * 0.1 }}
                >
                  <Card className={`border-l-4 ${
                    task.status === 'completed' ? 'border-green-500 bg-green-50' :
                    task.status === 'in_progress' ? 'border-blue-500 bg-blue-50' :
                    'border-gray-300'
                  }`}>
                    <CardContent className="p-6">
                      <div className="flex items-start justify-between mb-3">
                        <div className="flex-1">
                          <div className="flex items-center gap-3 mb-2">
                            <h3 className={`text-lg font-bold ${task.status === 'completed' ? 'line-through text-gray-500' : 'text-gray-900'}`}>
                              {task.due_time && `${task.due_time} `}
                              {task.task_name}
                            </h3>
                            <Badge className={getPriorityColor(task.priority)}>
                              {task.priority}
                            </Badge>
                            {task.task_type === 'weekly' && (
                              <Badge className="bg-purple-100 text-purple-800">Weekly</Badge>
                            )}
                            {task.task_type === 'monthly' && (
                              <Badge className="bg-orange-100 text-orange-800">Monthly</Badge>
                            )}
                          </div>
                          {task.description && (
                            <p className="text-sm text-gray-600 mb-2">{task.description}</p>
                          )}
                          {task.estimated_minutes && (
                            <p className="text-xs text-gray-500">
                              ⏱️ Estimated: {task.estimated_minutes} minutes
                            </p>
                          )}
                        </div>
                        
                        {/* Status Badge */}
                        {task.status === 'completed' && (
                          <CheckCircle className="w-8 h-8 text-green-600" />
                        )}
                        {task.status === 'in_progress' && (
                          <PlayCircle className="w-8 h-8 text-blue-600" />
                        )}
                        {task.status === 'pending' && (
                          <Clock className="w-8 h-8 text-gray-400" />
                        )}
                      </div>

                      {/* Task Actions */}
                      {task.status !== 'completed' && (
                        <div className="space-y-3 mt-4">
                          {/* Photo Upload */}
                          {task.requires_photo && (
                            <div>
                              <label className="text-sm font-medium text-gray-700 mb-1 block">
                                📸 Photo Evidence Required
                              </label>
                              {task.photo_url ? (
                                <img src={task.photo_url} alt="Evidence" className="w-full h-32 object-cover rounded-lg" />
                              ) : (
                                <div>
                                  <input
                                    type="file"
                                    accept="image/*"
                                    capture="environment"
                                    onChange={(e) => handlePhotoUpload(e, task)}
                                    className="hidden"
                                    id={`photo-${task.id}`}
                                    disabled={uploading}
                                  />
                                  <Button
                                    variant="outline"
                                    onClick={() => document.getElementById(`photo-${task.id}`).click()}
                                    disabled={uploading}
                                  >
                                    <Camera className="w-4 h-4 mr-2" />
                                    {uploading ? 'Uploading...' : 'Take Photo'}
                                  </Button>
                                </div>
                              )}
                            </div>
                          )}

                          {/* Linked Form */}
                          {task.linked_form_id && (
                            <Button variant="outline" className="w-full">
                              <FileText className="w-4 h-4 mr-2" />
                              Open Linked Form
                            </Button>
                          )}

                          {/* Notes */}
                          {task.status === 'in_progress' && (
                            <Textarea
                              placeholder="Add completion notes..."
                              value={selectedTask?.id === task.id ? taskNotes : ''}
                              onChange={(e) => {
                                setSelectedTask(task);
                                setTaskNotes(e.target.value);
                              }}
                              rows={2}
                            />
                          )}

                          {/* Action Buttons */}
                          <div className="flex gap-2">
                            {task.status === 'pending' && (
                              <Button
                                onClick={() => handleStartTask(task)}
                                className="flex-1 bg-blue-600 hover:bg-blue-700"
                              >
                                <PlayCircle className="w-4 h-4 mr-2" />
                                Start Task
                              </Button>
                            )}
                            {task.status === 'in_progress' && (
                              <Button
                                onClick={() => handleCompleteTask(task)}
                                className="flex-1 bg-green-600 hover:bg-green-700"
                                disabled={task.requires_photo && !task.photo_url}
                              >
                                <CheckCircle className="w-4 h-4 mr-2" />
                                Mark Complete
                              </Button>
                            )}
                          </div>
                        </div>
                      )}

                      {/* Completion Info */}
                      {task.status === 'completed' && task.completed_at && (
                        <div className="mt-3 p-3 bg-green-50 rounded-lg text-sm">
                          <p className="text-green-800">
                            ✅ Completed at {format(new Date(task.completed_at), 'h:mm a')}
                          </p>
                          {task.notes && (
                            <p className="text-gray-600 mt-1">{task.notes}</p>
                          )}
                        </div>
                      )}
                    </CardContent>
                  </Card>
                </motion.div>
              ))}
          </div>
        )}
      </div>
    </div>
  );
}