import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { useQuery } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import {
  Trophy,
  Star,
  TrendingUp,
  Award,
  Target,
  CheckCircle,
  Clock,
  Zap,
  Users,
  Home,
  ArrowLeft,
  Medal,
  Crown,
  Flame
} from "lucide-react";
import { format } from "date-fns";
import { Link, useNavigate } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { motion } from "framer-motion";

export default function PerformanceDashboard() {
  const navigate = useNavigate();
  const [timeframe, setTimeframe] = useState('week'); // week, month, all_time

  const { data: user } = useQuery({
    queryKey: ['currentUser'],
    queryFn: () => base44.auth.me(),
  });

  const isManager = user?.position === 'manager' || user?.position === 'owner' || user?.role === 'admin';

  // Fetch AURA Staff Scores
  const { data: staffScores = [], isLoading } = useQuery({
    queryKey: ['staffPerformanceScores', timeframe],
    queryFn: async () => {
      // Get all active staff
      const staff = await base44.entities.User.filter({ status: 'active' });
      
      const scores = await Promise.all(staff.map(async (member) => {
        // Get hygiene score
        const hygieneScores = await base44.entities.HygieneUserScore.filter({
          staff_email: member.email
        });
        const hygieneScore = hygieneScores[0];

        // Get attendance records
        const attendance = await base44.entities.AttendanceRecord.filter({
          staff_email: member.email
        });

        // Get task completion
        const tasks = await base44.entities.AutoGeneratedTask.filter({
          assigned_to_email: member.email
        });

        // Get form completion
        const formResponses = await base44.entities.FormResponse.filter({
          staff_email: member.email,
          status: 'submitted'
        });

        // Calculate AURA Score
        const auraScore = calculateAuraScore({
          hygiene: hygieneScore,
          attendance,
          tasks,
          formResponses
        });

        return {
          ...member,
          auraScore,
          hygieneScore: hygieneScore || null,
          attendance: attendance || [],
          tasks: tasks || [],
          formResponses: formResponses || []
        };
      }));

      // Sort by AURA score
      return scores.sort((a, b) => b.auraScore.total - a.auraScore.total);
    },
    enabled: isManager,
  });

  // Fetch individual staff score
  const { data: myScore } = useQuery({
    queryKey: ['myPerformanceScore', user?.email, timeframe],
    queryFn: async () => {
      if (!user?.email) return null;

      const hygieneScores = await base44.entities.HygieneUserScore.filter({
        staff_email: user.email
      });
      const hygieneScore = hygieneScores[0];

      const attendance = await base44.entities.AttendanceRecord.filter({
        staff_email: user.email
      });

      const tasks = await base44.entities.AutoGeneratedTask.filter({
        assigned_to_email: user.email
      });

      const formResponses = await base44.entities.FormResponse.filter({
        staff_email: user.email,
        status: 'submitted'
      });

      const auraScore = calculateAuraScore({
        hygiene: hygieneScore,
        attendance,
        tasks,
        formResponses
      });

      return {
        ...user,
        auraScore,
        hygieneScore,
        attendance,
        tasks,
        formResponses
      };
    },
    enabled: !!user?.email,
  });

  function calculateAuraScore({ hygiene, attendance, tasks, formResponses }) {
    let total = 0;
    const breakdown = {};

    // 1. Hygiene Score (30 points)
    if (hygiene) {
      const hygienePoints = Math.min(30, (hygiene.total_points || 0) / 10);
      breakdown.hygiene = Math.round(hygienePoints);
      total += hygienePoints;
    } else {
      breakdown.hygiene = 0;
    }

    // 2. Punctuality (25 points)
    if (attendance.length > 0) {
      const onTime = attendance.filter(a => a.status === 'on_time' || (a.lateness_minutes || 0) <= 5).length;
      const punctualityRate = (onTime / attendance.length);
      const punctualityPoints = punctualityRate * 25;
      breakdown.punctuality = Math.round(punctualityPoints);
      total += punctualityPoints;
    } else {
      breakdown.punctuality = 0;
    }

    // 3. Task Completion (25 points)
    if (tasks.length > 0) {
      const completed = tasks.filter(t => t.status === 'completed').length;
      const completionRate = (completed / tasks.length);
      const taskPoints = completionRate * 25;
      breakdown.tasks = Math.round(taskPoints);
      total += taskPoints;
    } else {
      breakdown.tasks = 0;
    }

    // 4. Form Compliance (20 points)
    if (formResponses.length > 0) {
      const passed = formResponses.filter(r => r.passed || r.status === 'approved').length;
      const complianceRate = (passed / formResponses.length);
      const formPoints = complianceRate * 20;
      breakdown.forms = Math.round(formPoints);
      total += formPoints;
    } else {
      breakdown.forms = 0;
    }

    return {
      total: Math.round(total),
      breakdown,
      grade: getGrade(total),
      rank: getRank(total)
    };
  }

  function getGrade(score) {
    if (score >= 90) return { letter: 'A+', color: 'text-green-600', badge: 'Exceptional' };
    if (score >= 80) return { letter: 'A', color: 'text-green-500', badge: 'Excellent' };
    if (score >= 70) return { letter: 'B', color: 'text-blue-500', badge: 'Very Good' };
    if (score >= 60) return { letter: 'C', color: 'text-yellow-500', badge: 'Good' };
    if (score >= 50) return { letter: 'D', color: 'text-orange-500', badge: 'Needs Improvement' };
    return { letter: 'F', color: 'text-red-500', badge: 'Urgent Attention' };
  }

  function getRank(score) {
    if (score >= 95) return { title: 'AURA Champion', icon: Crown, color: 'text-yellow-500' };
    if (score >= 85) return { title: 'Rising Star', icon: Star, color: 'text-purple-500' };
    if (score >= 70) return { title: 'Solid Performer', icon: Medal, color: 'text-blue-500' };
    if (score >= 50) return { title: 'Team Player', icon: Users, color: 'text-green-500' };
    return { title: 'Developing', icon: Target, color: 'text-gray-500' };
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-purple-50 to-blue-50 p-6 md:p-8">
      <div className="max-w-7xl mx-auto">
        {/* Back Buttons */}
        <div className="flex gap-3 mb-6">
          <Link to={createPageUrl("PerformanceGrowth")}>
            <Button variant="outline" size="sm">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back
            </Button>
          </Link>
          <Link to={createPageUrl("Dashboard")}>
            <Button variant="outline" size="sm">
              <Home className="w-4 h-4 mr-2" />
              Dashboard
            </Button>
          </Link>
        </div>

        {/* Header */}
        <div className="mb-8 text-center">
          <motion.div
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
          >
            <div className="flex items-center justify-center gap-3 mb-4">
              <Trophy className="w-12 h-12 text-yellow-500" />
              <h1 className="text-4xl font-bold text-gray-900">
                AURA Performance Dashboard
              </h1>
            </div>
            <p className="text-xl text-gray-600">
              Track your performance, earn badges, climb the leaderboard
            </p>
          </motion.div>
        </div>

        {/* My Score Card (for non-managers) */}
        {!isManager && myScore && (
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="mb-8"
          >
            <Card className="bg-gradient-to-br from-purple-600 to-indigo-600 text-white border-none shadow-2xl">
              <CardContent className="p-8">
                <div className="grid md:grid-cols-2 gap-8">
                  {/* Score Display */}
                  <div className="text-center">
                    <p className="text-purple-200 mb-2">Your AURA Score</p>
                    <div className="text-8xl font-bold mb-4">{myScore.auraScore.total}</div>
                    <Badge className="bg-white/20 text-white text-lg px-4 py-2">
                      Grade: {myScore.auraScore.grade.letter}
                    </Badge>
                    <div className="mt-4">
                      {React.createElement(myScore.auraScore.rank.icon, {
                        className: `w-12 h-12 ${myScore.auraScore.rank.color} mx-auto mb-2`
                      })}
                      <p className="text-xl font-semibold">{myScore.auraScore.rank.title}</p>
                    </div>
                  </div>

                  {/* Breakdown */}
                  <div className="space-y-4">
                    <h3 className="text-xl font-bold mb-4">Score Breakdown</h3>
                    
                    <div>
                      <div className="flex justify-between mb-2">
                        <span>🧼 Hygiene</span>
                        <span className="font-bold">{myScore.auraScore.breakdown.hygiene}/30</span>
                      </div>
                      <Progress value={(myScore.auraScore.breakdown.hygiene / 30) * 100} className="bg-white/20" />
                    </div>

                    <div>
                      <div className="flex justify-between mb-2">
                        <span>⏰ Punctuality</span>
                        <span className="font-bold">{myScore.auraScore.breakdown.punctuality}/25</span>
                      </div>
                      <Progress value={(myScore.auraScore.breakdown.punctuality / 25) * 100} className="bg-white/20" />
                    </div>

                    <div>
                      <div className="flex justify-between mb-2">
                        <span>✅ Task Completion</span>
                        <span className="font-bold">{myScore.auraScore.breakdown.tasks}/25</span>
                      </div>
                      <Progress value={(myScore.auraScore.breakdown.tasks / 25) * 100} className="bg-white/20" />
                    </div>

                    <div>
                      <div className="flex justify-between mb-2">
                        <span>📋 Form Compliance</span>
                        <span className="font-bold">{myScore.auraScore.breakdown.forms}/20</span>
                      </div>
                      <Progress value={(myScore.auraScore.breakdown.forms / 20) * 100} className="bg-white/20" />
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </motion.div>
        )}

        {/* Leaderboard (for managers) */}
        {isManager && (
          <Card className="mb-8">
            <CardHeader>
              <CardTitle className="flex items-center justify-between">
                <span className="flex items-center gap-2">
                  <Trophy className="w-6 h-6 text-yellow-500" />
                  Team Leaderboard
                </span>
                <div className="flex gap-2">
                  <Button
                    variant={timeframe === 'week' ? 'default' : 'outline'}
                    size="sm"
                    onClick={() => setTimeframe('week')}
                  >
                    Week
                  </Button>
                  <Button
                    variant={timeframe === 'month' ? 'default' : 'outline'}
                    size="sm"
                    onClick={() => setTimeframe('month')}
                  >
                    Month
                  </Button>
                  <Button
                    variant={timeframe === 'all_time' ? 'default' : 'outline'}
                    size="sm"
                    onClick={() => setTimeframe('all_time')}
                  >
                    All Time
                  </Button>
                </div>
              </CardTitle>
            </CardHeader>
            <CardContent>
              {isLoading ? (
                <div className="text-center py-12">
                  <div className="animate-spin rounded-full h-12 w-12 border-b-4 border-purple-600 mx-auto mb-4"></div>
                  <p className="text-gray-600">Calculating scores...</p>
                </div>
              ) : (
                <div className="space-y-4">
                  {staffScores.slice(0, 10).map((staff, index) => {
                    const RankIcon = staff.auraScore.rank.icon;
                    return (
                      <motion.div
                        key={staff.email}
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: index * 0.1 }}
                        className={`p-4 rounded-lg border-2 ${
                          index === 0 ? 'bg-gradient-to-r from-yellow-50 to-amber-50 border-yellow-300' :
                          index === 1 ? 'bg-gradient-to-r from-gray-50 to-slate-50 border-gray-300' :
                          index === 2 ? 'bg-gradient-to-r from-orange-50 to-amber-50 border-orange-300' :
                          'bg-white border-gray-200'
                        }`}
                      >
                        <div className="flex items-center gap-4">
                          {/* Rank */}
                          <div className="text-center w-12">
                            {index === 0 && <Crown className="w-8 h-8 text-yellow-500 mx-auto" />}
                            {index === 1 && <Medal className="w-8 h-8 text-gray-400 mx-auto" />}
                            {index === 2 && <Medal className="w-8 h-8 text-orange-600 mx-auto" />}
                            {index > 2 && <span className="text-2xl font-bold text-gray-400">#{index + 1}</span>}
                          </div>

                          {/* Staff Info */}
                          <div className="flex-1">
                            <div className="flex items-center gap-3 mb-2">
                              <h3 className="text-lg font-bold text-gray-900">{staff.full_name}</h3>
                              <Badge className={`${staff.auraScore.rank.color.replace('text-', 'bg-').replace('500', '100')} ${staff.auraScore.rank.color} border-0`}>
                                <RankIcon className="w-4 h-4 mr-1" />
                                {staff.auraScore.rank.title}
                              </Badge>
                            </div>
                            <div className="flex items-center gap-4 text-sm text-gray-600">
                              <span>🧼 {staff.auraScore.breakdown.hygiene}/30</span>
                              <span>⏰ {staff.auraScore.breakdown.punctuality}/25</span>
                              <span>✅ {staff.auraScore.breakdown.tasks}/25</span>
                              <span>📋 {staff.auraScore.breakdown.forms}/20</span>
                            </div>
                          </div>

                          {/* Score */}
                          <div className="text-right">
                            <div className="text-4xl font-bold text-gray-900 mb-1">
                              {staff.auraScore.total}
                            </div>
                            <Badge className={`${staff.auraScore.grade.color.replace('text-', 'bg-').replace('600', '100')} ${staff.auraScore.grade.color} border-0`}>
                              {staff.auraScore.grade.letter}
                            </Badge>
                          </div>
                        </div>
                      </motion.div>
                    );
                  })}
                </div>
              )}
            </CardContent>
          </Card>
        )}

        {/* Performance Insights */}
        <div className="grid md:grid-cols-3 gap-6">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-lg">
                <Flame className="w-5 h-5 text-orange-500" />
                Current Streak
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-center">
                <div className="text-5xl font-bold text-orange-500 mb-2">
                  {myScore?.hygieneScore?.current_streak || 0}
                </div>
                <p className="text-gray-600">Days Perfect</p>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-lg">
                <Star className="w-5 h-5 text-yellow-500" />
                Badges Earned
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-center">
                <div className="text-5xl font-bold text-yellow-500 mb-2">
                  {myScore?.hygieneScore?.badges_earned?.length || 0}
                </div>
                <p className="text-gray-600">Achievements</p>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-lg">
                <TrendingUp className="w-5 h-5 text-green-500" />
                Global Rank
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-center">
                <div className="text-5xl font-bold text-green-500 mb-2">
                  #{myScore?.hygieneScore?.rank_global || '-'}
                </div>
                <p className="text-gray-600">Overall Ranking</p>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}