import React, { useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Calendar,
  ChevronLeft,
  ChevronRight,
  Plus,
  Users,
  Clock,
  CheckCircle,
  AlertCircle,
  Copy,
  Printer,
  Download,
  Zap,
  ArrowLeft,
  Home,
  Edit,
  Trash2,
  Eye,
  RefreshCw,
} from "lucide-react";
import { format, startOfWeek, addDays, addWeeks, subWeeks, getWeek, parseISO, isSameDay } from "date-fns";
import { Link } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { motion, AnimatePresence } from "framer-motion";

const POSITIONS = [
  { name: "Manager", color: "bg-pink-100", textColor: "text-pink-900", borderColor: "border-pink-500" },
  { name: "Chef", color: "bg-amber-100", textColor: "text-amber-900", borderColor: "border-amber-500" },
  { name: "Barista", color: "bg-green-100", textColor: "text-green-900", borderColor: "border-green-500" },
  { name: "Front of House", color: "bg-blue-100", textColor: "text-blue-900", borderColor: "border-blue-500" },
  { name: "Server", color: "bg-purple-100", textColor: "text-purple-900", borderColor: "border-purple-500" },
  { name: "Line Cook", color: "bg-orange-100", textColor: "text-orange-900", borderColor: "border-orange-500" },
  { name: "Bartender", color: "bg-indigo-100", textColor: "text-indigo-900", borderColor: "border-indigo-500" },
  { name: "Cleaner", color: "bg-gray-100", textColor: "text-gray-900", borderColor: "border-gray-500" },
];

export default function SmartScheduler() {
  const queryClient = useQueryClient();
  const [currentWeekStart, setCurrentWeekStart] = useState(startOfWeek(new Date(), { weekStartsOn: 1 }));
  const [showAddShiftDialog, setShowAddShiftDialog] = useState(false);
  const [selectedShift, setSelectedShift] = useState(null);
  const [showTaskPreview, setShowTaskPreview] = useState(false);
  const [previewShift, setPreviewShift] = useState(null);
  const [generatingTasks, setGeneratingTasks] = useState(false);

  const [shiftForm, setShiftForm] = useState({
    staff_email: "",
    staff_name: "",
    role: "",
    department: "",
    shift_date: "",
    shift_type: "mid_shift",
    start_time: "",
    end_time: "",
    status: "scheduled",
  });

  const weekDates = Array.from({ length: 7 }, (_, i) => addDays(currentWeekStart, i));
  const weekNumber = getWeek(currentWeekStart);

  const { data: user } = useQuery({
    queryKey: ['currentUser'],
    queryFn: () => base44.auth.me(),
  });

  const { data: shifts = [], isLoading } = useQuery({
    queryKey: ['weeklyShifts', format(currentWeekStart, 'yyyy-MM-dd')],
    queryFn: async () => {
      const weekEnd = addDays(currentWeekStart, 6);
      const allShifts = await base44.entities.Shift.list();
      
      return allShifts.filter(shift => {
        const shiftDate = parseISO(shift.shift_date);
        return shiftDate >= currentWeekStart && shiftDate <= weekEnd;
      });
    },
  });

  const { data: users = [] } = useQuery({
    queryKey: ['users'],
    queryFn: () => base44.entities.User.list(),
  });

  const { data: responsibilities = [] } = useQuery({
    queryKey: ['responsibilities'],
    queryFn: () => base44.entities.RoleResponsibility.list(),
  });

  const { data: tasks = [] } = useQuery({
    queryKey: ['autoGeneratedTasks'],
    queryFn: () => base44.entities.AutoGeneratedTask.list(),
  });

  const createShiftMutation = useMutation({
    mutationFn: (data) => base44.entities.Shift.create(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['weeklyShifts'] });
      resetForm();
    },
  });

  const updateShiftMutation = useMutation({
    mutationFn: ({ id, data }) => base44.entities.Shift.update(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['weeklyShifts'] });
      setSelectedShift(null);
    },
  });

  const deleteShiftMutation = useMutation({
    mutationFn: (id) => base44.entities.Shift.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['weeklyShifts'] });
    },
  });

  const generateTasksMutation = useMutation({
    mutationFn: async (shift) => {
      // Find responsibilities for this role
      const roleResponsibilities = responsibilities.find(
        r => r.position === shift.role && r.is_active && r.auto_assign_enabled
      );

      if (!roleResponsibilities) {
        throw new Error(`No responsibilities found for role: ${shift.role}`);
      }

      const tasksToCreate = [];
      const shiftDate = shift.shift_date;
      const dayOfWeek = format(parseISO(shiftDate), 'EEEE').toLowerCase();

      // Generate daily tasks
      if (roleResponsibilities.daily_tasks) {
        roleResponsibilities.daily_tasks.forEach((task, index) => {
          const dueTime = calculateDueTime(shift.end_time, task.estimated_minutes || 30);
          
          tasksToCreate.push({
            task_name: task.task_name || task,
            description: task.description || "",
            assigned_to_email: shift.staff_email,
            assigned_to_name: shift.staff_name,
            role: shift.role,
            department: shift.department || roleResponsibilities.department,
            shift_id: shift.id,
            shift_date: shiftDate,
            linked_responsibility_id: roleResponsibilities.id,
            linked_form_id: task.linked_form_id || null,
            priority: task.priority || "medium",
            estimated_minutes: task.estimated_minutes || 30,
            due_time: dueTime,
            status: "pending",
            requires_photo: task.requires_photo || false,
            created_automatically: true,
            task_type: "daily",
          });
        });
      }

      // Generate weekly tasks if today matches
      if (roleResponsibilities.weekly_tasks) {
        roleResponsibilities.weekly_tasks.forEach((task) => {
          if (task.day_of_week === dayOfWeek) {
            const dueTime = calculateDueTime(shift.end_time, task.estimated_minutes || 60);
            
            tasksToCreate.push({
              task_name: task.task_name || task,
              description: task.description || "",
              assigned_to_email: shift.staff_email,
              assigned_to_name: shift.staff_name,
              role: shift.role,
              department: shift.department || roleResponsibilities.department,
              shift_id: shift.id,
              shift_date: shiftDate,
              linked_responsibility_id: roleResponsibilities.id,
              linked_form_id: task.linked_form_id || null,
              priority: task.priority || "medium",
              estimated_minutes: task.estimated_minutes || 60,
              due_time: dueTime,
              status: "pending",
              requires_photo: task.requires_photo || false,
              created_automatically: true,
              task_type: "weekly",
            });
          }
        });
      }

      // Bulk create tasks
      if (tasksToCreate.length > 0) {
        await base44.entities.AutoGeneratedTask.bulkCreate(tasksToCreate);
        
        // Update shift to mark tasks as generated
        await base44.entities.Shift.update(shift.id, {
          auto_generated_tasks: true,
          tasks_generated_at: new Date().toISOString(),
        });

        // Send notification to staff
        await base44.entities.TaskNotification.create({
          notification_type: "shift_tasks_ready",
          recipient_email: shift.staff_email,
          recipient_name: shift.staff_name,
          sender_type: "system",
          title: "📋 Your Shift Tasks Are Ready",
          message: `Your tasks for ${format(parseISO(shift.shift_date), 'EEEE, MMM d')} have been prepared. ${tasksToCreate.length} tasks assigned.`,
          related_shift_id: shift.id,
          priority: "info",
          action_url: createPageUrl("MyTasks"),
        });
      }

      return { tasksCreated: tasksToCreate.length, shift };
    },
    onSuccess: (result) => {
      queryClient.invalidateQueries({ queryKey: ['weeklyShifts'] });
      queryClient.invalidateQueries({ queryKey: ['autoGeneratedTasks'] });
      alert(`✅ Successfully generated ${result.tasksCreated} tasks for this shift!`);
    },
    onError: (error) => {
      alert(`❌ Error generating tasks: ${error.message}`);
    },
  });

  const calculateDueTime = (shiftEndTime, minutesBefore) => {
    const [hours, minutes] = shiftEndTime.split(':').map(Number);
    const totalMinutes = hours * 60 + minutes - minutesBefore;
    const dueHours = Math.floor(totalMinutes / 60);
    const dueMinutes = totalMinutes % 60;
    return `${String(dueHours).padStart(2, '0')}:${String(dueMinutes).padStart(2, '0')}`;
  };

  const resetForm = () => {
    setShowAddShiftDialog(false);
    setSelectedShift(null);
    setShiftForm({
      staff_email: "",
      staff_name: "",
      role: "",
      department: "",
      shift_date: "",
      shift_type: "mid_shift",
      start_time: "",
      end_time: "",
      status: "scheduled",
    });
  };

  const handleSaveShift = async () => {
    if (!shiftForm.staff_email || !shiftForm.shift_date || !shiftForm.start_time || !shiftForm.end_time) {
      alert("Please fill in all required fields");
      return;
    }

    const staffMember = users.find(u => u.email === shiftForm.staff_email);
    
    const data = {
      ...shiftForm,
      staff_name: staffMember?.full_name || shiftForm.staff_name,
      role: shiftForm.role || staffMember?.position,
      department: shiftForm.department || getDefaultDepartment(staffMember?.position),
      status: "scheduled",
      auto_generated_tasks: false,
    };

    if (selectedShift) {
      await updateShiftMutation.mutateAsync({
        id: selectedShift.id,
        data
      });
    } else {
      const newShift = await createShiftMutation.mutateAsync(data);
      
      // Auto-generate tasks if role has responsibilities
      const hasResponsibilities = responsibilities.some(
        r => r.position === data.role && r.is_active && r.auto_assign_enabled
      );
      
      if (hasResponsibilities && confirm("🤖 Auto-generate tasks for this shift?")) {
        await generateTasksMutation.mutateAsync(newShift);
      }
    }
  };

  const handleGenerateTasks = async (shift) => {
    if (!shift.auto_generated_tasks) {
      setGeneratingTasks(true);
      await generateTasksMutation.mutateAsync(shift);
      setGeneratingTasks(false);
    } else {
      if (confirm("Tasks already generated. Regenerate and replace existing tasks?")) {
        // Delete existing tasks for this shift
        const existingTasks = tasks.filter(t => t.shift_id === shift.id);
        for (const task of existingTasks) {
          await base44.entities.AutoGeneratedTask.delete(task.id);
        }
        
        setGeneratingTasks(true);
        await generateTasksMutation.mutateAsync(shift);
        setGeneratingTasks(false);
      }
    }
  };

  const handlePreviewTasks = (shift) => {
    setPreviewShift(shift);
    setShowTaskPreview(true);
  };

  const getDefaultDepartment = (position) => {
    const deptMap = {
      'chef': 'kitchen',
      'line_cook': 'kitchen',
      'server': 'front_of_house',
      'bartender': 'bar',
      'manager': 'management',
      'cleaner': 'cleaning',
    };
    return deptMap[position?.toLowerCase()] || 'general';
  };

  const getShiftsByPositionAndDate = (position, date) => {
    return shifts.filter(shift => {
      return (
        shift.role === position &&
        isSameDay(parseISO(shift.shift_date), date)
      );
    });
  };

  const handleEditShift = (shift) => {
    setSelectedShift(shift);
    setShiftForm({
      staff_email: shift.staff_email,
      staff_name: shift.staff_name,
      role: shift.role,
      department: shift.department,
      shift_date: shift.shift_date,
      shift_type: shift.shift_type,
      start_time: shift.start_time,
      end_time: shift.end_time,
      status: shift.status,
    });
    setShowAddShiftDialog(true);
  };

  const handleDeleteShift = async (shiftId) => {
    if (confirm("Are you sure you want to delete this shift? This will also delete all auto-generated tasks.")) {
      // Delete associated tasks
      const shiftTasks = tasks.filter(t => t.shift_id === shiftId);
      for (const task of shiftTasks) {
        await base44.entities.AutoGeneratedTask.delete(task.id);
      }
      
      await deleteShiftMutation.mutateAsync(shiftId);
    }
  };

  const calculateWeeklyStats = () => {
    const totalShifts = shifts.length;
    const shiftsWithTasks = shifts.filter(s => s.auto_generated_tasks).length;
    const totalHours = shifts.reduce((sum, shift) => {
      const [startHour, startMin] = shift.start_time.split(':').map(Number);
      const [endHour, endMin] = shift.end_time.split(':').map(Number);
      const minutes = (endHour * 60 + endMin) - (startHour * 60 + startMin);
      return sum + (minutes / 60);
    }, 0);

    return { totalShifts, shiftsWithTasks, totalHours: totalHours.toFixed(1) };
  };

  const stats = calculateWeeklyStats();
  const positionsWithShifts = POSITIONS.filter(pos => 
    shifts.some(shift => shift.role === pos.name)
  );

  return (
    <div className="p-6 md:p-8 bg-gray-50 min-h-screen">
      <div className="max-w-[1600px] mx-auto">
        {/* Back Navigation */}
        <div className="flex gap-3 mb-6">
          <Link to={createPageUrl("StaffRota")}>
            <Button variant="outline" size="sm">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Shift & Rota
            </Button>
          </Link>
          <Link to={createPageUrl("Dashboard")}>
            <Button variant="outline" size="sm">
              <Home className="w-4 h-4 mr-2" />
              Dashboard
            </Button>
          </Link>
        </div>

        {/* Header */}
        <div className="mb-6">
          <div className="flex flex-wrap justify-between items-start gap-4 mb-4">
            <div>
              <h1 className="text-3xl font-bold text-gray-900 mb-2">
                🤖 Smart Scheduler – Role-Based Planning
              </h1>
              <p className="text-gray-600">
                Automatically assign tasks based on position and responsibilities
              </p>
            </div>
            <div className="flex gap-2">
              <Link to={createPageUrl("ManagerDashboard")}>
                <Button variant="outline" size="sm">
                  <Users className="w-4 h-4 mr-2" />
                  Manage Responsibilities
                </Button>
              </Link>
              <Button variant="outline" size="sm" onClick={() => window.print()}>
                <Printer className="w-4 h-4 mr-2" />
                Print
              </Button>
              <Button onClick={() => setShowAddShiftDialog(true)} className="bg-blue-600">
                <Plus className="w-4 h-4 mr-2" />
                Add Shift
              </Button>
            </div>
          </div>

          {/* Week Navigation & Stats */}
          <Card className="bg-gradient-to-r from-blue-50 to-green-50 border-none">
            <CardContent className="p-4">
              <div className="flex flex-wrap items-center justify-between gap-4">
                <div className="flex items-center gap-4">
                  <Button variant="outline" size="icon" onClick={() => setCurrentWeekStart(subWeeks(currentWeekStart, 1))}>
                    <ChevronLeft className="w-5 h-5" />
                  </Button>
                  <div className="text-center">
                    <h2 className="text-xl font-bold text-gray-900">Week {weekNumber}</h2>
                    <p className="text-sm text-gray-600">
                      {format(currentWeekStart, 'dd MMM')} - {format(addDays(currentWeekStart, 6), 'dd MMM yyyy')}
                    </p>
                  </div>
                  <Button variant="outline" size="icon" onClick={() => setCurrentWeekStart(addWeeks(currentWeekStart, 1))}>
                    <ChevronRight className="w-5 h-5" />
                  </Button>
                  <Button variant="outline" size="sm" onClick={() => setCurrentWeekStart(startOfWeek(new Date(), { weekStartsOn: 1 }))}>
                    Today
                  </Button>
                </div>

                <div className="flex gap-6">
                  <div className="text-center">
                    <p className="text-2xl font-bold text-blue-600">{stats.totalShifts}</p>
                    <p className="text-xs text-gray-600">Total Shifts</p>
                  </div>
                  <div className="text-center">
                    <p className="text-2xl font-bold text-green-600">{stats.shiftsWithTasks}</p>
                    <p className="text-xs text-gray-600">Tasks Generated</p>
                  </div>
                  <div className="text-center">
                    <p className="text-2xl font-bold text-purple-600">{stats.totalHours}h</p>
                    <p className="text-xs text-gray-600">Total Hours</p>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Gantt Chart */}
        <Card className="bg-white border-none shadow-lg overflow-hidden">
          <CardContent className="p-0">
            {/* Table Header */}
            <div className="grid grid-cols-8 border-b-2 border-gray-300 bg-gradient-to-r from-blue-50 to-blue-100">
              <div className="p-4 font-bold text-gray-900 border-r border-gray-300">
                Position
              </div>
              {weekDates.map((date, index) => {
                const isToday = isSameDay(date, new Date());
                return (
                  <div 
                    key={index}
                    className={`p-4 text-center border-r border-gray-300 ${isToday ? 'bg-yellow-100' : ''}`}
                  >
                    <div className={`font-bold ${isToday ? 'text-blue-600' : 'text-gray-900'}`}>
                      {format(date, 'EEE dd')}
                    </div>
                    <div className="text-xs text-gray-500 mt-1">
                      {format(date, 'MMM')}
                    </div>
                  </div>
                );
              })}
            </div>

            {/* Position Rows */}
            {isLoading ? (
              <div className="p-12 text-center">
                <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto mb-4" />
                <p className="text-gray-500">Loading schedule...</p>
              </div>
            ) : positionsWithShifts.length === 0 ? (
              <div className="p-12 text-center text-gray-500">
                <Calendar className="w-16 h-16 text-gray-400 mx-auto mb-4" />
                <p className="text-lg font-semibold mb-2">No Shifts Scheduled</p>
                <p className="text-sm mb-4">Click "Add Shift" to start planning</p>
                <Button onClick={() => setShowAddShiftDialog(true)} className="bg-blue-600">
                  <Plus className="w-4 h-4 mr-2" />
                  Add First Shift
                </Button>
              </div>
            ) : (
              <AnimatePresence>
                {positionsWithShifts.map((position, posIndex) => (
                  <motion.div
                    key={posIndex}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: posIndex * 0.05 }}
                    className={`grid grid-cols-8 border-b border-gray-200 ${position.color}`}
                  >
                    {/* Position Label */}
                    <div className={`p-4 font-semibold ${position.textColor} border-r border-gray-200 flex items-center`}>
                      {position.name}
                    </div>

                    {/* Days */}
                    {weekDates.map((date, dayIndex) => {
                      const dayShifts = getShiftsByPositionAndDate(position.name, date);
                      const isToday = isSameDay(date, new Date());
                      
                      return (
                        <div 
                          key={dayIndex}
                          className={`p-2 border-r border-gray-200 min-h-[100px] relative ${isToday ? 'bg-yellow-50/30' : ''}`}
                        >
                          {dayShifts.map((shift, shiftIndex) => (
                            <motion.div
                              key={shiftIndex}
                              initial={{ scale: 0.8, opacity: 0 }}
                              animate={{ scale: 1, opacity: 1 }}
                              transition={{ delay: shiftIndex * 0.1 }}
                              className={`bg-white rounded-lg shadow-sm p-2 mb-2 border-l-4 ${position.borderColor} hover:shadow-md transition-all cursor-pointer relative group`}
                            >
                              <div className="flex items-start gap-2">
                                <div className={`w-8 h-8 rounded-full ${position.color} flex items-center justify-center flex-shrink-0`}>
                                  <span className="text-xs font-bold">{shift.staff_name?.charAt(0) || '?'}</span>
                                </div>
                                <div className="flex-1 min-w-0">
                                  <p className="text-xs font-semibold text-gray-900 truncate">
                                    {shift.staff_name || shift.staff_email}
                                  </p>
                                  <p className="text-xs text-gray-600">
                                    {shift.start_time} - {shift.end_time}
                                  </p>
                                  <div className="flex items-center gap-1 mt-1 flex-wrap">
                                    {shift.auto_generated_tasks ? (
                                      <Badge className="bg-green-100 text-green-800 text-[10px] px-1 py-0">
                                        <CheckCircle className="w-2 h-2 mr-1" />
                                        Tasks Ready
                                      </Badge>
                                    ) : (
                                      <Badge className="bg-yellow-100 text-yellow-800 text-[10px] px-1 py-0">
                                        <AlertCircle className="w-2 h-2 mr-1" />
                                        No Tasks
                                      </Badge>
                                    )}
                                    {shift.status === 'in_progress' && (
                                      <Badge className="bg-blue-100 text-blue-800 text-[10px] px-1 py-0">
                                        Live
                                      </Badge>
                                    )}
                                  </div>
                                </div>
                              </div>

                              {/* Hover Actions */}
                              <div className="absolute top-1 right-1 opacity-0 group-hover:opacity-100 transition-opacity flex gap-1">
                                {!shift.auto_generated_tasks && (
                                  <button
                                    onClick={() => handleGenerateTasks(shift)}
                                    className="p-1 bg-green-600 text-white rounded hover:bg-green-700"
                                    title="Auto-generate tasks"
                                  >
                                    <Zap className="w-3 h-3" />
                                  </button>
                                )}
                                <button
                                  onClick={() => handlePreviewTasks(shift)}
                                  className="p-1 bg-blue-600 text-white rounded hover:bg-blue-700"
                                  title="Preview tasks"
                                >
                                  <Eye className="w-3 h-3" />
                                </button>
                                <button
                                  onClick={() => handleEditShift(shift)}
                                  className="p-1 bg-gray-600 text-white rounded hover:bg-gray-700"
                                  title="Edit shift"
                                >
                                  <Edit className="w-3 h-3" />
                                </button>
                                <button
                                  onClick={() => handleDeleteShift(shift.id)}
                                  className="p-1 bg-red-600 text-white rounded hover:bg-red-700"
                                  title="Delete shift"
                                >
                                  <Trash2 className="w-3 h-3" />
                                </button>
                              </div>
                            </motion.div>
                          ))}
                        </div>
                      );
                    })}
                  </motion.div>
                ))}
              </AnimatePresence>
            )}
          </CardContent>
        </Card>

        {/* Legend */}
        <Card className="mt-6">
          <CardContent className="p-4">
            <div className="flex flex-wrap gap-4 items-center">
              <p className="font-semibold text-gray-900">Legend:</p>
              <Badge className="bg-green-100 text-green-800">
                <CheckCircle className="w-3 h-3 mr-1" />
                Tasks Generated
              </Badge>
              <Badge className="bg-yellow-100 text-yellow-800">
                <AlertCircle className="w-3 h-3 mr-1" />
                No Tasks Yet
              </Badge>
              <Badge className="bg-blue-100 text-blue-800">Live Shift</Badge>
              <Button variant="ghost" size="sm" className="ml-auto">
                <Zap className="w-4 h-4 mr-2 text-green-600" />
                Auto-Generate Tasks
              </Button>
              <Button variant="ghost" size="sm">
                <Eye className="w-4 h-4 mr-2 text-blue-600" />
                Preview Tasks
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Add/Edit Shift Dialog */}
      <Dialog open={showAddShiftDialog} onOpenChange={(open) => !open && resetForm()}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>{selectedShift ? 'Edit Shift' : 'Add New Shift'}</DialogTitle>
          </DialogHeader>
          <div className="space-y-4 mt-4">
            <div className="grid md:grid-cols-2 gap-4">
              <div>
                <Label>Staff Member *</Label>
                <Select 
                  value={shiftForm.staff_email} 
                  onValueChange={(value) => {
                    const staff = users.find(u => u.email === value);
                    setShiftForm({
                      ...shiftForm,
                      staff_email: value,
                      staff_name: staff?.full_name || "",
                      role: staff?.position || "",
                      department: getDefaultDepartment(staff?.position),
                    });
                  }}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select staff member" />
                  </SelectTrigger>
                  <SelectContent>
                    {users.map((u) => (
                      <SelectItem key={u.email} value={u.email}>
                        {u.full_name} ({u.position})
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div>
                <Label>Date *</Label>
                <Input
                  type="date"
                  value={shiftForm.shift_date}
                  onChange={(e) => setShiftForm({ ...shiftForm, shift_date: e.target.value })}
                />
              </div>

              <div>
                <Label>Start Time *</Label>
                <Input
                  type="time"
                  value={shiftForm.start_time}
                  onChange={(e) => setShiftForm({ ...shiftForm, start_time: e.target.value })}
                />
              </div>

              <div>
                <Label>End Time *</Label>
                <Input
                  type="time"
                  value={shiftForm.end_time}
                  onChange={(e) => setShiftForm({ ...shiftForm, end_time: e.target.value })}
                />
              </div>

              <div>
                <Label>Shift Type</Label>
                <Select value={shiftForm.shift_type} onValueChange={(value) => setShiftForm({ ...shiftForm, shift_type: value })}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="opening">Opening</SelectItem>
                    <SelectItem value="mid_shift">Mid Shift</SelectItem>
                    <SelectItem value="closing">Closing</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div>
                <Label>Role</Label>
                <Input
                  value={shiftForm.role}
                  onChange={(e) => setShiftForm({ ...shiftForm, role: e.target.value })}
                  placeholder="Auto-filled from staff profile"
                />
              </div>
            </div>

            {/* Auto-Task Generation Preview */}
            {shiftForm.role && (
              <Card className="bg-blue-50 border-blue-200">
                <CardContent className="p-4">
                  <div className="flex items-start gap-3">
                    <Zap className="w-5 h-5 text-blue-600 mt-0.5" />
                    <div className="flex-1">
                      <p className="font-semibold text-blue-900 mb-1">Auto-Task Generation</p>
                      <p className="text-sm text-blue-800">
                        {responsibilities.some(r => r.position === shiftForm.role && r.is_active && r.auto_assign_enabled)
                          ? `✅ Tasks will be auto-generated for "${shiftForm.role}" when you save this shift.`
                          : `⚠️ No responsibilities defined for "${shiftForm.role}". Tasks won't be auto-generated.`
                        }
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            )}

            <div className="flex justify-end gap-3 pt-4">
              <Button variant="outline" onClick={resetForm}>
                Cancel
              </Button>
              <Button onClick={handleSaveShift} className="bg-blue-600">
                {selectedShift ? 'Update Shift' : 'Create Shift'}
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>

      {/* Task Preview Dialog */}
      <Dialog open={showTaskPreview} onOpenChange={setShowTaskPreview}>
        <DialogContent className="max-w-3xl">
          <DialogHeader>
            <DialogTitle>Task Preview: {previewShift?.staff_name}</DialogTitle>
          </DialogHeader>
          {previewShift && (
            <div className="mt-4 space-y-4">
              <div className="flex items-center justify-between p-4 bg-gray-50 rounded-lg">
                <div>
                  <p className="font-semibold text-gray-900">{previewShift.role}</p>
                  <p className="text-sm text-gray-600">
                    {format(parseISO(previewShift.shift_date), 'EEEE, MMM d')} • {previewShift.start_time} - {previewShift.end_time}
                  </p>
                </div>
                {!previewShift.auto_generated_tasks && (
                  <Button 
                    onClick={() => {
                      setShowTaskPreview(false);
                      handleGenerateTasks(previewShift);
                    }}
                    className="bg-green-600"
                    disabled={generatingTasks}
                  >
                    <Zap className="w-4 h-4 mr-2" />
                    {generatingTasks ? 'Generating...' : 'Generate Tasks'}
                  </Button>
                )}
              </div>

              {/* Show tasks if generated */}
              {previewShift.auto_generated_tasks ? (
                <div className="space-y-2">
                  <p className="font-semibold text-gray-900">Generated Tasks:</p>
                  {tasks
                    .filter(t => t.shift_id === previewShift.id)
                    .map((task, index) => (
                      <Card key={index} className="border-l-4 border-blue-500">
                        <CardContent className="p-4">
                          <div className="flex items-start justify-between">
                            <div>
                              <p className="font-medium text-gray-900">{task.task_name}</p>
                              <p className="text-sm text-gray-600 mt-1">{task.description}</p>
                              <div className="flex items-center gap-2 mt-2">
                                <Badge variant="outline" className="text-xs">
                                  {task.task_type}
                                </Badge>
                                <Badge className="text-xs">
                                  Due: {task.due_time}
                                </Badge>
                                <Badge className={`text-xs ${
                                  task.priority === 'high' ? 'bg-red-100 text-red-800' :
                                  task.priority === 'medium' ? 'bg-yellow-100 text-yellow-800' :
                                  'bg-green-100 text-green-800'
                                }`}>
                                  {task.priority}
                                </Badge>
                              </div>
                            </div>
                            <Badge className={
                              task.status === 'completed' ? 'bg-green-100 text-green-800' :
                              task.status === 'in_progress' ? 'bg-blue-100 text-blue-800' :
                              task.status === 'overdue' ? 'bg-red-100 text-red-800' :
                              'bg-gray-100 text-gray-800'
                            }>
                              {task.status}
                            </Badge>
                          </div>
                        </CardContent>
                      </Card>
                    ))}
                </div>
              ) : (
                <div className="p-8 text-center bg-yellow-50 rounded-lg">
                  <AlertCircle className="w-12 h-12 text-yellow-600 mx-auto mb-3" />
                  <p className="font-semibold text-yellow-900 mb-2">No Tasks Generated Yet</p>
                  <p className="text-sm text-yellow-800">
                    Click "Generate Tasks" to automatically create tasks based on role responsibilities
                  </p>
                </div>
              )}
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}