import React, { useState, useMemo } from "react";
import { base44 } from "@/api/base44Client";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import {
  DollarSign,
  Download,
  Printer,
  CheckCircle,
  AlertCircle,
  Clock,
  TrendingUp,
  Award,
  Calendar,
  ChevronLeft,
  ChevronRight,
  RefreshCw,
  Eye,
  Edit,
  Send,
  ArrowLeft,
  Home,
  FileText,
  BarChart3,
  Users,
} from "lucide-react";
import { format, startOfWeek, addDays, getWeek, addWeeks, subWeeks, parseISO, differenceInMinutes, getDay } from "date-fns";
import { Link } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { motion } from "framer-motion";

export default function StaffWagesReport() {
  const queryClient = useQueryClient();
  const [currentWeekStart, setCurrentWeekStart] = useState(startOfWeek(new Date(), { weekStartsOn: 1 }));
  const [selectedDepartment, setSelectedDepartment] = useState("all");
  const [showGenerateDialog, setShowGenerateDialog] = useState(false);
  const [selectedStaff, setSelectedStaff] = useState(null);
  const [showDetailsDialog, setShowDetailsDialog] = useState(false);
  const [generating, setGenerating] = useState(false);

  const weekNumber = getWeek(currentWeekStart);
  const weekEnd = addDays(currentWeekStart, 6);

  const { data: user } = useQuery({
    queryKey: ['currentUser'],
    queryFn: () => base44.auth.me(),
  });

  const isManager = user?.position === 'manager' || user?.position === 'owner' || user?.role === 'admin';

  // Get all data for the week
  const { data: attendanceRecords = [] } = useQuery({
    queryKey: ['weeklyAttendance', format(currentWeekStart, 'yyyy-MM-dd')],
    queryFn: async () => {
      const all = await base44.entities.AttendanceRecord.list('-shift_date');
      return all.filter(r => {
        const date = parseISO(r.shift_date);
        return date >= currentWeekStart && date <= weekEnd;
      });
    },
  });

  const { data: allTasks = [] } = useQuery({
    queryKey: ['weeklyTasks', format(currentWeekStart, 'yyyy-MM-dd')],
    queryFn: async () => {
      const all = await base44.entities.AutoGeneratedTask.list();
      return all.filter(t => {
        const date = parseISO(t.shift_date);
        return date >= currentWeekStart && date <= weekEnd;
      });
    },
  });

  const { data: checklistExecutions = [] } = useQuery({
    queryKey: ['weeklyChecklists', format(currentWeekStart, 'yyyy-MM-dd')],
    queryFn: async () => {
      const all = await base44.entities.ChecklistExecution.list();
      return all.filter(c => {
        const date = parseISO(c.execution_date);
        return date >= currentWeekStart && date <= weekEnd;
      });
    },
  });

  const { data: allStaff = [] } = useQuery({
    queryKey: ['allStaff'],
    queryFn: () => base44.entities.User.list(),
  });

  const { data: teamMembers = [] } = useQuery({
    queryKey: ['teamMembers'],
    queryFn: () => base44.entities.TeamMember.list(),
  });

  const { data: wageRates = [] } = useQuery({
    queryKey: ['wageRates'],
    queryFn: () => base44.entities.WageRate.list(),
  });

  const { data: payrollRecords = [] } = useQuery({
    queryKey: ['payrollRecords', weekNumber],
    queryFn: () => base44.entities.PayrollRecord.filter({ week_number: weekNumber }),
  });

  const { data: performanceMetrics = [] } = useQuery({
    queryKey: ['performanceMetrics', weekNumber],
    queryFn: () => base44.entities.PerformanceMetric.filter({ week_number: weekNumber }),
  });

  // Calculate comprehensive staff data
  const staffWagesData = useMemo(() => {
    const staffMap = new Map();

    attendanceRecords.forEach(record => {
      if (!record.actual_clock_in || !record.actual_clock_out) return;

      const staff = allStaff.find(s => s.email === record.staff_email);
      const teamMember = teamMembers.find(tm => tm.staff_email === record.staff_email);
      
      if (!staff) return;

      // Filter by department
      if (selectedDepartment !== 'all' && teamMember?.department !== selectedDepartment) return;

      if (!staffMap.has(record.staff_email)) {
        const wageRate = wageRates.find(wr => 
          wr.role === (teamMember?.position || staff.position) && 
          wr.is_active
        );

        staffMap.set(record.staff_email, {
          email: record.staff_email,
          name: record.staff_name || staff.full_name,
          position: teamMember?.position || staff.position || 'Staff',
          department: teamMember?.department || 'N/A',
          base_hourly_rate: wageRate?.base_hourly_rate || teamMember?.hourly_rate || 12.50,
          overtime_rate: wageRate?.overtime_rate || 1.5,
          night_shift_bonus: wageRate?.night_shift_bonus || 0,
          weekend_bonus: wageRate?.weekend_bonus || 0,
          total_hours: 0,
          regular_hours: 0,
          overtime_hours: 0,
          night_hours: 0,
          weekend_hours: 0,
          total_shifts: 0,
          late_count: 0,
          early_departure_count: 0,
          perfect_attendance: 0,
          tasks_completed: 0,
          tasks_assigned: 0,
          checklists_completed: 0,
          checklists_total: 0,
          daily_breakdown: {},
        });
      }

      const staffData = staffMap.get(record.staff_email);
      
      // Add hours
      const totalHours = record.total_hours || 0;
      const overtimeHours = record.overtime_hours || 0;
      const regularHours = totalHours - overtimeHours;
      
      staffData.total_hours += totalHours;
      staffData.regular_hours += regularHours;
      staffData.overtime_hours += overtimeHours;
      staffData.total_shifts += 1;
      
      // Check if night shift (10 PM - 6 AM)
      const clockInTime = parseISO(record.actual_clock_in);
      const clockOutTime = parseISO(record.actual_clock_out);
      const startHour = clockInTime.getHours();
      const endHour = clockOutTime.getHours();
      if (startHour >= 22 || startHour < 6 || endHour >= 22 || endHour < 6) {
        staffData.night_hours += totalHours;
      }

      // Check if weekend
      const shiftDate = parseISO(record.shift_date);
      const dayOfWeek = getDay(shiftDate);
      if (dayOfWeek === 0 || dayOfWeek === 6) {
        staffData.weekend_hours += totalHours;
      }
      
      if (record.lateness_minutes > 5) staffData.late_count += 1;
      if (record.early_departure_minutes > 5) staffData.early_departure_count += 1;
      if (record.lateness_minutes <= 5 && record.early_departure_minutes <= 5) {
        staffData.perfect_attendance += 1;
      }

      // Daily breakdown
      const day = format(shiftDate, 'EEE');
      if (!staffData.daily_breakdown[day]) {
        staffData.daily_breakdown[day] = 0;
      }
      staffData.daily_breakdown[day] += totalHours;
    });

    // Add task data
    allTasks.forEach(task => {
      if (staffMap.has(task.assigned_to_email)) {
        const staffData = staffMap.get(task.assigned_to_email);
        staffData.tasks_assigned += 1;
        if (task.status === 'completed') {
          staffData.tasks_completed += 1;
        }
      }
    });

    // Add checklist data
    checklistExecutions.forEach(checklist => {
      if (staffMap.has(checklist.assigned_to_email)) {
        const staffData = staffMap.get(checklist.assigned_to_email);
        staffData.checklists_total += 1;
        if (checklist.status === 'completed') {
          staffData.checklists_completed += 1;
        }
      }
    });

    // Calculate wages and performance
    Array.from(staffMap.values()).forEach(staff => {
      // Calculate pay
      staff.regular_pay = staff.regular_hours * staff.base_hourly_rate;
      staff.overtime_pay = staff.overtime_hours * staff.base_hourly_rate * staff.overtime_rate;
      staff.night_bonus = staff.night_hours * staff.night_shift_bonus;
      staff.weekend_bonus_pay = staff.weekend_hours * staff.weekend_bonus;
      
      // Calculate performance
      const attendanceRate = staff.total_shifts > 0 ? (staff.perfect_attendance / staff.total_shifts) * 100 : 0;
      const punctualityScore = staff.total_shifts > 0 ? ((staff.total_shifts - staff.late_count) / staff.total_shifts) * 100 : 0;
      const taskCompletionRate = staff.tasks_assigned > 0 ? (staff.tasks_completed / staff.tasks_assigned) * 100 : 0;
      const checklistAccuracy = staff.checklists_total > 0 ? (staff.checklists_completed / staff.checklists_total) * 100 : 0;
      
      staff.attendance_rate = attendanceRate;
      staff.punctuality_score = punctualityScore;
      staff.task_completion_rate = taskCompletionRate;
      staff.checklist_accuracy = checklistAccuracy;
      
      // Final performance score (weighted average)
      staff.performance_score = (
        (punctualityScore * 0.25) +
        (attendanceRate * 0.20) +
        (taskCompletionRate * 0.30) +
        (checklistAccuracy * 0.25)
      );
      
      // Performance bonus (if score > 85)
      staff.performance_bonus = 0;
      if (staff.performance_score >= 85) {
        staff.performance_bonus = staff.regular_pay * 0.10; // 10% bonus
      } else if (staff.performance_score >= 75) {
        staff.performance_bonus = staff.regular_pay * 0.05; // 5% bonus
      }
      
      // Deductions
      staff.late_penalty = staff.late_count * 10; // £10 per late arrival
      staff.total_deductions = staff.late_penalty;
      
      // Total pay
      staff.gross_pay = staff.regular_pay + staff.overtime_pay + staff.night_bonus + staff.weekend_bonus_pay + staff.performance_bonus;
      staff.net_pay = staff.gross_pay - staff.total_deductions;
      
      // Performance tier
      if (staff.performance_score >= 90) {
        staff.performance_tier = 'exceptional';
      } else if (staff.performance_score >= 75) {
        staff.performance_tier = 'exceeds_expectations';
      } else if (staff.performance_score >= 60) {
        staff.performance_tier = 'meets_expectations';
      } else {
        staff.performance_tier = 'needs_improvement';
      }
    });

    return Array.from(staffMap.values()).sort((a, b) => b.total_hours - a.total_hours);
  }, [attendanceRecords, allStaff, teamMembers, wageRates, allTasks, checklistExecutions, selectedDepartment]);

  // Calculate summary stats
  const summaryStats = useMemo(() => {
    return staffWagesData.reduce((acc, staff) => {
      acc.totalStaff += 1;
      acc.totalHours += staff.total_hours;
      acc.totalOvertimeHours += staff.overtime_hours;
      acc.totalRegularPay += staff.regular_pay;
      acc.totalOvertimePay += staff.overtime_pay;
      acc.totalBonuses += staff.performance_bonus + staff.night_bonus + staff.weekend_bonus_pay;
      acc.totalDeductions += staff.total_deductions;
      acc.totalGrossPay += staff.gross_pay;
      acc.totalNetPay += staff.net_pay;
      return acc;
    }, {
      totalStaff: 0,
      totalHours: 0,
      totalOvertimeHours: 0,
      totalRegularPay: 0,
      totalOvertimePay: 0,
      totalBonuses: 0,
      totalDeductions: 0,
      totalGrossPay: 0,
      totalNetPay: 0,
    });
  }, [staffWagesData]);

  // Generate payroll records mutation
  const generatePayrollMutation = useMutation({
    mutationFn: async () => {
      const records = [];
      
      for (const staff of staffWagesData) {
        // Check if record already exists
        const existing = payrollRecords.find(pr => 
          pr.staff_email === staff.email && 
          pr.week_number === weekNumber
        );

        if (existing) {
          // Update existing
          await base44.entities.PayrollRecord.update(existing.id, {
            total_hours: staff.total_hours,
            regular_hours: staff.regular_hours,
            overtime_hours: staff.overtime_hours,
            night_hours: staff.night_hours,
            weekend_hours: staff.weekend_hours,
            total_shifts: staff.total_shifts,
            late_count: staff.late_count,
            early_departure_count: staff.early_departure_count,
            regular_pay: staff.regular_pay,
            overtime_pay: staff.overtime_pay,
            night_shift_bonus: staff.night_bonus,
            weekend_bonus: staff.weekend_bonus_pay,
            performance_bonus: staff.performance_bonus,
            deductions: {
              late_penalties: staff.late_penalty,
              other: 0,
              notes: ''
            },
            total_gross_pay: staff.gross_pay,
            total_net_pay: staff.net_pay,
            performance_score: staff.performance_score,
            tasks_completed: staff.tasks_completed,
            tasks_assigned: staff.tasks_assigned,
            task_completion_rate: staff.task_completion_rate,
            checklists_completed: staff.checklists_completed,
            checklist_accuracy: staff.checklist_accuracy,
            status: 'generated',
            generated_at: new Date().toISOString(),
            generated_by: user.email,
          });
        } else {
          // Create new
          await base44.entities.PayrollRecord.create({
            staff_email: staff.email,
            staff_name: staff.name,
            role: staff.position,
            department: staff.department,
            period_start: format(currentWeekStart, 'yyyy-MM-dd'),
            period_end: format(weekEnd, 'yyyy-MM-dd'),
            week_number: weekNumber,
            total_hours: staff.total_hours,
            regular_hours: staff.regular_hours,
            overtime_hours: staff.overtime_hours,
            night_hours: staff.night_hours,
            weekend_hours: staff.weekend_hours,
            total_shifts: staff.total_shifts,
            late_count: staff.late_count,
            early_departure_count: staff.early_departure_count,
            base_hourly_rate: staff.base_hourly_rate,
            overtime_rate: staff.overtime_rate,
            regular_pay: staff.regular_pay,
            overtime_pay: staff.overtime_pay,
            night_shift_bonus: staff.night_bonus,
            weekend_bonus: staff.weekend_bonus_pay,
            performance_bonus: staff.performance_bonus,
            deductions: {
              late_penalties: staff.late_penalty,
              other: 0,
              notes: ''
            },
            total_gross_pay: staff.gross_pay,
            total_net_pay: staff.net_pay,
            performance_score: staff.performance_score,
            tasks_completed: staff.tasks_completed,
            tasks_assigned: staff.tasks_assigned,
            task_completion_rate: staff.task_completion_rate,
            checklists_completed: staff.checklists_completed,
            checklist_accuracy: staff.checklist_accuracy,
            status: 'generated',
            generated_at: new Date().toISOString(),
            generated_by: user.email,
          });
        }

        // Create or update performance metric
        const existingMetric = performanceMetrics.find(pm => 
          pm.staff_email === staff.email && 
          pm.week_number === weekNumber
        );

        if (existingMetric) {
          await base44.entities.PerformanceMetric.update(existingMetric.id, {
            punctuality_score: staff.punctuality_score,
            attendance_rate: staff.attendance_rate,
            task_completion_rate: staff.task_completion_rate,
            checklist_accuracy: staff.checklist_accuracy,
            final_score: staff.performance_score,
            performance_tier: staff.performance_tier,
            bonus_eligible: staff.performance_bonus > 0,
            bonus_amount: staff.performance_bonus,
            generated_at: new Date().toISOString(),
          });
        } else {
          await base44.entities.PerformanceMetric.create({
            staff_email: staff.email,
            staff_name: staff.name,
            week_number: weekNumber,
            week_start: format(currentWeekStart, 'yyyy-MM-dd'),
            week_end: format(weekEnd, 'yyyy-MM-dd'),
            punctuality_score: staff.punctuality_score,
            attendance_rate: staff.attendance_rate,
            task_completion_rate: staff.task_completion_rate,
            checklist_accuracy: staff.checklist_accuracy,
            manager_rating: 0,
            peer_recognition_count: 0,
            total_badges_earned: 0,
            total_points: 0,
            final_score: staff.performance_score,
            performance_tier: staff.performance_tier,
            bonus_eligible: staff.performance_bonus > 0,
            bonus_amount: staff.performance_bonus,
            generated_at: new Date().toISOString(),
          });
        }
      }

      return records;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['payrollRecords'] });
      queryClient.invalidateQueries({ queryKey: ['performanceMetrics'] });
      alert(`✅ Generated payroll for ${staffWagesData.length} staff members!`);
      setShowGenerateDialog(false);
    },
    onError: (error) => {
      alert('❌ Error generating payroll: ' + error.message);
    }
  });

  const handleGeneratePayroll = async () => {
    setGenerating(true);
    try {
      await generatePayrollMutation.mutateAsync();
    } finally {
      setGenerating(false);
    }
  };

  const exportToCSV = () => {
    const csvRows = [];
    
    // Header
    csvRows.push([
      'Staff Wages Report',
      `Week ${weekNumber} (${format(currentWeekStart, 'dd/MM/yyyy')} - ${format(weekEnd, 'dd/MM/yyyy')})`
    ]);
    csvRows.push([]);
    csvRows.push(['Staff Name', 'Position', 'Dept', 'Hours', 'Overtime', 'Rate', 'Reg Pay', 'OT Pay', 'Bonuses', 'Deductions', 'Net Pay', 'Performance']);
    
    // Data rows
    staffWagesData.forEach(staff => {
      csvRows.push([
        staff.name,
        staff.position,
        staff.department,
        staff.total_hours.toFixed(2),
        staff.overtime_hours.toFixed(2),
        `£${staff.base_hourly_rate.toFixed(2)}`,
        `£${staff.regular_pay.toFixed(2)}`,
        `£${staff.overtime_pay.toFixed(2)}`,
        `£${(staff.performance_bonus + staff.night_bonus + staff.weekend_bonus_pay).toFixed(2)}`,
        `£${staff.total_deductions.toFixed(2)}`,
        `£${staff.net_pay.toFixed(2)}`,
        `${staff.performance_score.toFixed(1)}%`
      ]);
    });
    
    // Totals
    csvRows.push([]);
    csvRows.push(['TOTALS', '', '', 
      summaryStats.totalHours.toFixed(2),
      summaryStats.totalOvertimeHours.toFixed(2),
      '',
      `£${summaryStats.totalRegularPay.toFixed(2)}`,
      `£${summaryStats.totalOvertimePay.toFixed(2)}`,
      `£${summaryStats.totalBonuses.toFixed(2)}`,
      `£${summaryStats.totalDeductions.toFixed(2)}`,
      `£${summaryStats.totalNetPay.toFixed(2)}`,
      ''
    ]);
    
    const csvContent = csvRows.map(row => row.join(',')).join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `wages-report-week-${weekNumber}-${format(new Date(), 'yyyy-MM-dd')}.csv`;
    a.click();
  };

  const getPerformanceTierColor = (tier) => {
    switch (tier) {
      case 'exceptional':
        return 'bg-purple-100 text-purple-800 border-purple-200';
      case 'exceeds_expectations':
        return 'bg-green-100 text-green-800 border-green-200';
      case 'meets_expectations':
        return 'bg-blue-100 text-blue-800 border-blue-200';
      case 'needs_improvement':
        return 'bg-red-100 text-red-800 border-red-200';
      default:
        return 'bg-gray-100 text-gray-800 border-gray-200';
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 p-6 md:p-8">
      <div className="max-w-7xl mx-auto">
        {/* Back Navigation */}
        <div className="flex gap-3 mb-6">
          <Link to={createPageUrl("ManagerDashboard")}>
            <Button variant="outline" size="sm">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Manager Dashboard
            </Button>
          </Link>
          <Link to={createPageUrl("Dashboard")}>
            <Button variant="outline" size="sm">
              <Home className="w-4 h-4 mr-2" />
              Home
            </Button>
          </Link>
        </div>

        {/* Header */}
        <div className="mb-8">
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center gap-4">
              <Button variant="outline" size="icon" onClick={() => setCurrentWeekStart(subWeeks(currentWeekStart, 1))}>
                <ChevronLeft className="w-5 h-5" />
              </Button>
              <div className="text-center">
                <h1 className="text-3xl font-bold text-gray-900 flex items-center gap-3">
                  <DollarSign className="w-8 h-8 text-green-600" />
                  Staff Wages Report
                </h1>
                <p className="text-gray-600 mt-1">
                  Week {weekNumber}: {format(currentWeekStart, 'dd MMM')} - {format(weekEnd, 'dd MMM yyyy')}
                </p>
              </div>
              <Button variant="outline" size="icon" onClick={() => setCurrentWeekStart(addWeeks(currentWeekStart, 1))}>
                <ChevronRight className="w-5 h-5" />
              </Button>
            </div>

            <div className="flex gap-2">
              <Select value={selectedDepartment} onValueChange={setSelectedDepartment}>
                <SelectTrigger className="w-48">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Departments</SelectItem>
                  <SelectItem value="kitchen">Kitchen</SelectItem>
                  <SelectItem value="front_of_house">Front of House</SelectItem>
                  <SelectItem value="bar">Bar</SelectItem>
                  <SelectItem value="management">Management</SelectItem>
                  <SelectItem value="cleaning">Cleaning</SelectItem>
                  <SelectItem value="maintenance">Maintenance</SelectItem>
                </SelectContent>
              </Select>
              <Button variant="outline" onClick={exportToCSV}>
                <Download className="w-4 h-4 mr-2" />
                Export CSV
              </Button>
              <Button variant="outline" onClick={() => window.print()}>
                <Printer className="w-4 h-4 mr-2" />
                Print
              </Button>
              <Button 
                onClick={() => setShowGenerateDialog(true)}
                className="bg-green-600 hover:bg-green-700"
              >
                <RefreshCw className="w-4 h-4 mr-2" />
                Generate Payroll
              </Button>
            </div>
          </div>
        </div>

        {/* Summary Stats */}
        <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-5 gap-4 mb-8">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
            <Card>
              <CardContent className="p-4">
                <div className="flex items-center justify-between mb-2">
                  <Users className="w-6 h-6 text-blue-600" />
                </div>
                <p className="text-2xl font-bold text-gray-900">{summaryStats.totalStaff}</p>
                <p className="text-xs text-gray-600">Staff Members</p>
              </CardContent>
            </Card>
          </motion.div>

          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.05 }}>
            <Card>
              <CardContent className="p-4">
                <div className="flex items-center justify-between mb-2">
                  <Clock className="w-6 h-6 text-purple-600" />
                </div>
                <p className="text-2xl font-bold text-gray-900">{summaryStats.totalHours.toFixed(1)}</p>
                <p className="text-xs text-gray-600">Total Hours</p>
              </CardContent>
            </Card>
          </motion.div>

          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
            <Card>
              <CardContent className="p-4">
                <div className="flex items-center justify-between mb-2">
                  <TrendingUp className="w-6 h-6 text-orange-600" />
                </div>
                <p className="text-2xl font-bold text-gray-900">{summaryStats.totalOvertimeHours.toFixed(1)}</p>
                <p className="text-xs text-gray-600">Overtime Hours</p>
              </CardContent>
            </Card>
          </motion.div>

          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }}>
            <Card>
              <CardContent className="p-4">
                <div className="flex items-center justify-between mb-2">
                  <Award className="w-6 h-6 text-yellow-600" />
                </div>
                <p className="text-2xl font-bold text-gray-900">£{summaryStats.totalBonuses.toFixed(0)}</p>
                <p className="text-xs text-gray-600">Total Bonuses</p>
              </CardContent>
            </Card>
          </motion.div>

          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
            <Card className="bg-gradient-to-br from-green-50 to-emerald-50 border-green-200">
              <CardContent className="p-4">
                <div className="flex items-center justify-between mb-2">
                  <DollarSign className="w-6 h-6 text-green-600" />
                </div>
                <p className="text-2xl font-bold text-green-900">£{summaryStats.totalNetPay.toFixed(2)}</p>
                <p className="text-xs text-green-700 font-medium">Total Net Pay</p>
              </CardContent>
            </Card>
          </motion.div>
        </div>

        {/* Staff Wages Table */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <FileText className="w-5 h-5 text-gray-700" />
              Staff Breakdown
            </CardTitle>
          </CardHeader>
          <CardContent className="p-0">
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="bg-gray-50 border-b">
                  <tr>
                    <th className="text-left p-4 text-sm font-semibold text-gray-700">Staff</th>
                    <th className="text-left p-4 text-sm font-semibold text-gray-700">Position</th>
                    <th className="text-center p-4 text-sm font-semibold text-gray-700">Hours</th>
                    <th className="text-center p-4 text-sm font-semibold text-gray-700">OT</th>
                    <th className="text-center p-4 text-sm font-semibold text-gray-700">Rate</th>
                    <th className="text-center p-4 text-sm font-semibold text-gray-700">Regular</th>
                    <th className="text-center p-4 text-sm font-semibold text-gray-700">Overtime</th>
                    <th className="text-center p-4 text-sm font-semibold text-gray-700">Bonuses</th>
                    <th className="text-center p-4 text-sm font-semibold text-gray-700">Deductions</th>
                    <th className="text-right p-4 text-sm font-semibold text-gray-700">Net Pay</th>
                    <th className="text-center p-4 text-sm font-semibold text-gray-700">Performance</th>
                    <th className="text-center p-4 text-sm font-semibold text-gray-700">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {staffWagesData.map((staff, index) => (
                    <motion.tr
                      key={staff.email}
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: index * 0.02 }}
                      className="border-b hover:bg-gray-50 transition-colors"
                    >
                      <td className="p-4">
                        <div>
                          <p className="font-medium text-gray-900">{staff.name}</p>
                          <p className="text-xs text-gray-500">{staff.email}</p>
                        </div>
                      </td>
                      <td className="p-4">
                        <div>
                          <Badge className="bg-blue-100 text-blue-800 text-xs mb-1">
                            {staff.position ? staff.position.replace(/_/g, ' ') : 'Staff'}
                          </Badge>
                          <p className="text-xs text-gray-500">{staff.department}</p>
                        </div>
                      </td>
                      <td className="p-4 text-center">
                        <p className="font-semibold text-gray-900">{staff.total_hours.toFixed(1)}h</p>
                        <p className="text-xs text-gray-500">{staff.total_shifts} shifts</p>
                      </td>
                      <td className="p-4 text-center">
                        {staff.overtime_hours > 0 ? (
                          <Badge className="bg-orange-100 text-orange-800">
                            {staff.overtime_hours.toFixed(1)}h
                          </Badge>
                        ) : (
                          <span className="text-gray-400">-</span>
                        )}
                      </td>
                      <td className="p-4 text-center">
                        <p className="text-sm font-medium text-gray-900">£{staff.base_hourly_rate.toFixed(2)}</p>
                        <p className="text-xs text-gray-500">x{staff.overtime_rate} OT</p>
                      </td>
                      <td className="p-4 text-center">
                        <p className="text-sm text-gray-900">£{staff.regular_pay.toFixed(2)}</p>
                      </td>
                      <td className="p-4 text-center">
                        <p className="text-sm text-gray-900">£{staff.overtime_pay.toFixed(2)}</p>
                      </td>
                      <td className="p-4 text-center">
                        {(staff.performance_bonus + staff.night_bonus + staff.weekend_bonus_pay) > 0 ? (
                          <div className="text-sm text-green-700">
                            <p className="font-medium">£{(staff.performance_bonus + staff.night_bonus + staff.weekend_bonus_pay).toFixed(2)}</p>
                            {staff.performance_bonus > 0 && (
                              <p className="text-xs">Perf: £{staff.performance_bonus.toFixed(2)}</p>
                            )}
                          </div>
                        ) : (
                          <span className="text-gray-400">-</span>
                        )}
                      </td>
                      <td className="p-4 text-center">
                        {staff.total_deductions > 0 ? (
                          <Badge className="bg-red-100 text-red-800">
                            -£{staff.total_deductions.toFixed(2)}
                          </Badge>
                        ) : (
                          <span className="text-gray-400">-</span>
                        )}
                      </td>
                      <td className="p-4 text-right">
                        <div>
                          <p className="text-lg font-bold text-gray-900">£{staff.net_pay.toFixed(2)}</p>
                          <p className="text-xs text-gray-500">Gross: £{staff.gross_pay.toFixed(2)}</p>
                        </div>
                      </td>
                      <td className="p-4 text-center">
                        <Badge className={getPerformanceTierColor(staff.performance_tier)}>
                          {staff.performance_score.toFixed(0)}%
                        </Badge>
                        <p className="text-xs text-gray-500 mt-1 capitalize">
                          {staff.performance_tier ? staff.performance_tier.replace(/_/g, ' ') : 'N/A'}
                        </p>
                      </td>
                      <td className="p-4 text-center">
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => {
                            setSelectedStaff(staff);
                            setShowDetailsDialog(true);
                          }}
                        >
                          <Eye className="w-4 h-4" />
                        </Button>
                      </td>
                    </motion.tr>
                  ))}
                </tbody>
                <tfoot className="bg-gray-100 border-t-2 border-gray-300">
                  <tr>
                    <td colSpan="2" className="p-4 font-bold text-gray-900">TOTALS</td>
                    <td className="p-4 text-center font-bold text-gray-900">{summaryStats.totalHours.toFixed(1)}h</td>
                    <td className="p-4 text-center font-bold text-gray-900">{summaryStats.totalOvertimeHours.toFixed(1)}h</td>
                    <td className="p-4"></td>
                    <td className="p-4 text-center font-bold text-gray-900">£{summaryStats.totalRegularPay.toFixed(2)}</td>
                    <td className="p-4 text-center font-bold text-gray-900">£{summaryStats.totalOvertimePay.toFixed(2)}</td>
                    <td className="p-4 text-center font-bold text-green-700">£{summaryStats.totalBonuses.toFixed(2)}</td>
                    <td className="p-4 text-center font-bold text-red-700">-£{summaryStats.totalDeductions.toFixed(2)}</td>
                    <td className="p-4 text-right font-bold text-gray-900 text-lg">£{summaryStats.totalNetPay.toFixed(2)}</td>
                    <td colSpan="2" className="p-4"></td>
                  </tr>
                </tfoot>
              </table>
            </div>
          </CardContent>
        </Card>

        {/* Generate Payroll Dialog */}
        <Dialog open={showGenerateDialog} onOpenChange={setShowGenerateDialog}>
          <DialogContent>
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2">
                <RefreshCw className="w-5 h-5 text-green-600" />
                Generate Payroll Records
              </DialogTitle>
            </DialogHeader>
            <div className="space-y-4 py-4">
              <div className="p-4 bg-blue-50 rounded-lg border border-blue-200">
                <p className="text-sm text-blue-900">
                  <strong>This will create/update payroll records for:</strong>
                </p>
                <ul className="mt-2 space-y-1 text-sm text-blue-800">
                  <li>• {staffWagesData.length} staff members</li>
                  <li>• Week {weekNumber} ({format(currentWeekStart, 'dd MMM')} - {format(weekEnd, 'dd MMM')})</li>
                  <li>• Total payout: £{summaryStats.totalNetPay.toFixed(2)}</li>
                </ul>
              </div>

              <div className="p-4 bg-amber-50 rounded-lg border border-amber-200">
                <div className="flex items-start gap-2">
                  <AlertCircle className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
                  <div>
                    <p className="text-sm font-medium text-amber-900">Important:</p>
                    <p className="text-sm text-amber-800 mt-1">
                      Records will be saved with status "Generated". You'll need to verify and approve them before processing payments.
                    </p>
                  </div>
                </div>
              </div>

              <div className="space-y-2">
                <h4 className="font-semibold text-gray-900">What will be calculated:</h4>
                <ul className="text-sm text-gray-700 space-y-1 ml-4">
                  <li>✓ Regular hours and pay</li>
                  <li>✓ Overtime hours and pay (at {staffWagesData[0]?.overtime_rate || 1.5}x rate)</li>
                  <li>✓ Night shift bonuses</li>
                  <li>✓ Weekend bonuses</li>
                  <li>✓ Performance bonuses (based on scores)</li>
                  <li>✓ Late arrival penalties</li>
                  <li>✓ Task completion metrics</li>
                  <li>✓ Checklist accuracy metrics</li>
                </ul>
              </div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setShowGenerateDialog(false)}>
                Cancel
              </Button>
              <Button 
                onClick={handleGeneratePayroll}
                disabled={generating || generatePayrollMutation.isPending}
                className="bg-green-600 hover:bg-green-700"
              >
                {generating || generatePayrollMutation.isPending ? (
                  <>
                    <RefreshCw className="w-4 h-4 mr-2 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <CheckCircle className="w-4 h-4 mr-2" />
                    Generate Payroll
                  </>
                )}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>

        {/* Staff Details Dialog */}
        {selectedStaff && (
          <Dialog open={showDetailsDialog} onOpenChange={setShowDetailsDialog}>
            <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto">
              <DialogHeader>
                <DialogTitle className="text-2xl">
                  {selectedStaff.name} - Detailed Report
                </DialogTitle>
              </DialogHeader>
              <div className="space-y-6 py-4">
                {/* Summary Section */}
                <div className="grid grid-cols-3 gap-4">
                  <Card>
                    <CardContent className="p-4">
                      <p className="text-sm text-gray-600">Position</p>
                      <p className="text-lg font-bold text-gray-900 capitalize">
                        {selectedStaff.position ? selectedStaff.position.replace(/_/g, ' ') : 'N/A'}
                      </p>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardContent className="p-4">
                      <p className="text-sm text-gray-600">Department</p>
                      <p className="text-lg font-bold text-gray-900">{selectedStaff.department}</p>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardContent className="p-4">
                      <p className="text-sm text-gray-600">Total Shifts</p>
                      <p className="text-lg font-bold text-gray-900">{selectedStaff.total_shifts}</p>
                    </CardContent>
                  </Card>
                </div>

                {/* Hours Breakdown */}
                <Card>
                  <CardHeader>
                    <CardTitle className="text-lg">Hours Breakdown</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <p className="text-sm text-gray-600">Regular Hours</p>
                        <p className="text-2xl font-bold text-gray-900">{selectedStaff.regular_hours.toFixed(1)}h</p>
                      </div>
                      <div>
                        <p className="text-sm text-gray-600">Overtime Hours</p>
                        <p className="text-2xl font-bold text-orange-600">{selectedStaff.overtime_hours.toFixed(1)}h</p>
                      </div>
                      {selectedStaff.night_hours > 0 && (
                        <div>
                          <p className="text-sm text-gray-600">Night Shift Hours</p>
                          <p className="text-2xl font-bold text-purple-600">{selectedStaff.night_hours.toFixed(1)}h</p>
                        </div>
                      )}
                      {selectedStaff.weekend_hours > 0 && (
                        <div>
                          <p className="text-sm text-gray-600">Weekend Hours</p>
                          <p className="text-2xl font-bold text-blue-600">{selectedStaff.weekend_hours.toFixed(1)}h</p>
                        </div>
                      )}
                    </div>

                    <div className="mt-4 pt-4 border-t">
                      <p className="text-sm text-gray-600 mb-2">Daily Breakdown:</p>
                      <div className="grid grid-cols-7 gap-2">
                        {['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map(day => (
                          <div key={day} className="text-center p-2 bg-gray-50 rounded">
                            <p className="text-xs text-gray-600">{day}</p>
                            <p className="font-semibold text-gray-900">
                              {selectedStaff.daily_breakdown[day]?.toFixed(1) || '0'}h
                            </p>
                          </div>
                        ))}
                      </div>
                    </div>
                  </CardContent>
                </Card>

                {/* Pay Breakdown */}
                <Card>
                  <CardHeader>
                    <CardTitle className="text-lg">Pay Breakdown</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-3">
                      <div className="flex justify-between items-center">
                        <span className="text-gray-700">Base Rate:</span>
                        <span className="font-semibold">£{selectedStaff.base_hourly_rate.toFixed(2)}/hr</span>
                      </div>
                      <div className="flex justify-between items-center">
                        <span className="text-gray-700">Regular Pay:</span>
                        <span className="font-semibold">£{selectedStaff.regular_pay.toFixed(2)}</span>
                      </div>
                      <div className="flex justify-between items-center">
                        <span className="text-gray-700">Overtime Pay (x{selectedStaff.overtime_rate}):</span>
                        <span className="font-semibold text-orange-600">£{selectedStaff.overtime_pay.toFixed(2)}</span>
                      </div>
                      {selectedStaff.night_bonus > 0 && (
                        <div className="flex justify-between items-center">
                          <span className="text-gray-700">Night Shift Bonus:</span>
                          <span className="font-semibold text-purple-600">£{selectedStaff.night_bonus.toFixed(2)}</span>
                        </div>
                      )}
                      {selectedStaff.weekend_bonus_pay > 0 && (
                        <div className="flex justify-between items-center">
                          <span className="text-gray-700">Weekend Bonus:</span>
                          <span className="font-semibold text-blue-600">£{selectedStaff.weekend_bonus_pay.toFixed(2)}</span>
                        </div>
                      )}
                      {selectedStaff.performance_bonus > 0 && (
                        <div className="flex justify-between items-center">
                          <span className="text-gray-700">Performance Bonus:</span>
                          <span className="font-semibold text-green-600">£{selectedStaff.performance_bonus.toFixed(2)}</span>
                        </div>
                      )}
                      
                      <div className="border-t pt-3">
                        <div className="flex justify-between items-center">
                          <span className="text-gray-900 font-medium">Gross Pay:</span>
                          <span className="text-xl font-bold text-gray-900">£{selectedStaff.gross_pay.toFixed(2)}</span>
                        </div>
                      </div>
                      
                      {selectedStaff.total_deductions > 0 && (
                        <div className="flex justify-between items-center text-red-600">
                          <span>Deductions:</span>
                          <span className="font-semibold">-£{selectedStaff.total_deductions.toFixed(2)}</span>
                        </div>
                      )}
                      
                      <div className="border-t pt-3 bg-green-50 -mx-6 px-6 py-3">
                        <div className="flex justify-between items-center">
                          <span className="text-green-900 font-bold text-lg">Net Pay:</span>
                          <span className="text-2xl font-bold text-green-600">£{selectedStaff.net_pay.toFixed(2)}</span>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>

                {/* Performance Metrics */}
                <Card>
                  <CardHeader>
                    <CardTitle className="text-lg flex items-center gap-2">
                      <TrendingUp className="w-5 h-5 text-blue-600" />
                      Performance Metrics
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-4">
                      <div>
                        <div className="flex justify-between items-center mb-2">
                          <span className="text-sm text-gray-700">Overall Score</span>
                          <Badge className={getPerformanceTierColor(selectedStaff.performance_tier)}>
                            {selectedStaff.performance_score.toFixed(0)}% - {selectedStaff.performance_tier ? selectedStaff.performance_tier.replace(/_/g, ' ') : 'N/A'}
                          </Badge>
                        </div>
                      </div>

                      <div>
                        <div className="flex justify-between items-center mb-1">
                          <span className="text-sm text-gray-700">Punctuality</span>
                          <span className="text-sm font-semibold">{selectedStaff.punctuality_score.toFixed(0)}%</span>
                        </div>
                        <div className="w-full bg-gray-200 rounded-full h-2">
                          <div 
                            className="bg-blue-600 h-2 rounded-full" 
                            style={{ width: `${selectedStaff.punctuality_score}%` }}
                          />
                        </div>
                        {selectedStaff.late_count > 0 && (
                          <p className="text-xs text-red-600 mt-1">{selectedStaff.late_count} late arrival(s)</p>
                        )}
                      </div>

                      <div>
                        <div className="flex justify-between items-center mb-1">
                          <span className="text-sm text-gray-700">Attendance</span>
                          <span className="text-sm font-semibold">{selectedStaff.attendance_rate.toFixed(0)}%</span>
                        </div>
                        <div className="w-full bg-gray-200 rounded-full h-2">
                          <div 
                            className="bg-green-600 h-2 rounded-full" 
                            style={{ width: `${selectedStaff.attendance_rate}%` }}
                          />
                        </div>
                      </div>

                      <div>
                        <div className="flex justify-between items-center mb-1">
                          <span className="text-sm text-gray-700">Task Completion</span>
                          <span className="text-sm font-semibold">{selectedStaff.task_completion_rate.toFixed(0)}%</span>
                        </div>
                        <div className="w-full bg-gray-200 rounded-full h-2">
                          <div 
                            className="bg-purple-600 h-2 rounded-full" 
                            style={{ width: `${selectedStaff.task_completion_rate}%` }}
                          />
                        </div>
                        <p className="text-xs text-gray-600 mt-1">
                          {selectedStaff.tasks_completed} of {selectedStaff.tasks_assigned} tasks completed
                        </p>
                      </div>

                      <div>
                        <div className="flex justify-between items-center mb-1">
                          <span className="text-sm text-gray-700">Checklist Accuracy</span>
                          <span className="text-sm font-semibold">{selectedStaff.checklist_accuracy.toFixed(0)}%</span>
                        </div>
                        <div className="w-full bg-gray-200 rounded-full h-2">
                          <div 
                            className="bg-amber-600 h-2 rounded-full" 
                            style={{ width: `${selectedStaff.checklist_accuracy}%` }}
                          />
                        </div>
                        <p className="text-xs text-gray-600 mt-1">
                          {selectedStaff.checklists_completed} of {selectedStaff.checklists_total} checklists completed
                        </p>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </div>
              <DialogFooter>
                <Button variant="outline" onClick={() => setShowDetailsDialog(false)}>
                  Close
                </Button>
                <Button className="bg-blue-600 hover:bg-blue-700">
                  <Send className="w-4 h-4 mr-2" />
                  Send Report to Staff
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        )}
      </div>
    </div>
  );
}