
import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { useQuery } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend } from 'recharts';
import { Download, TrendingUp, Calendar, Users, CheckCircle, Clock, AlertTriangle, ArrowLeft, Home, AlertCircle } from "lucide-react";
import { format, subDays } from "date-fns";
import { Link } from "react-router-dom";
import { createPageUrl } from "@/utils";

export default function TaskReports() {
  const [timeRange, setTimeRange] = useState("7days");
  const [filterDepartment, setFilterDepartment] = useState("all");

  const { data: allTasks = [] } = useQuery({
    queryKey: ['allTasksForReports'],
    queryFn: () => base44.entities.AutoGeneratedTask.list('-shift_date', 500),
  });

  const { data: responsibilities = [] } = useQuery({
    queryKey: ['responsibilities'],
    queryFn: () => base44.entities.RoleResponsibility.list(),
  });

  const getDaysToShow = () => {
    switch (timeRange) {
      case '7days': return 7;
      case '30days': return 30;
      case '90days': return 90;
      default: return 7;
    }
  };

  const days = getDaysToShow();
  const dateRange = Array.from({ length: days }, (_, i) => {
    const date = new Date();
    date.setDate(date.getDate() - (days - 1 - i));
    return date;
  });

  // Filter tasks by department
  const filteredTasks = filterDepartment === 'all' 
    ? allTasks 
    : allTasks.filter(t => t.department === filterDepartment);

  // Completion trend data
  const completionTrendData = dateRange.map(date => {
    const dateStr = format(date, 'yyyy-MM-dd');
    const dayTasks = filteredTasks.filter(t => t.shift_date === dateStr);
    const completed = dayTasks.filter(t => t.status === 'completed').length;
    const total = dayTasks.length;
    const rate = total > 0 ? Math.round((completed / total) * 100) : 0;

    return {
      date: format(date, 'MMM d'),
      rate,
      completed,
      total,
    };
  });

  // Task status distribution
  const statusData = [
    { name: 'Completed', value: filteredTasks.filter(t => t.status === 'completed').length, color: '#10b981' },
    { name: 'In Progress', value: filteredTasks.filter(t => t.status === 'in_progress').length, color: '#3b82f6' },
    { name: 'Pending', value: filteredTasks.filter(t => t.status === 'pending').length, color: '#f59e0b' },
    { name: 'Overdue', value: filteredTasks.filter(t => t.status === 'overdue').length, color: '#ef4444' },
  ];

  // Completion by role
  const roleData = responsibilities.map(role => {
    const roleTasks = filteredTasks.filter(t => t.role === role.position);
    const completed = roleTasks.filter(t => t.status === 'completed').length;
    return {
      role: role.position.replace('_', ' '),
      completed,
      total: roleTasks.length,
      rate: roleTasks.length > 0 ? Math.round((completed / roleTasks.length) * 100) : 0,
    };
  }).filter(r => r.total > 0);

  // Top performers
  const staffPerformance = filteredTasks.reduce((acc, task) => {
    if (!acc[task.assigned_to_email]) {
      acc[task.assigned_to_email] = {
        name: task.assigned_to_name,
        email: task.assigned_to_email,
        completed: 0,
        total: 0,
      };
    }
    acc[task.assigned_to_email].total++;
    if (task.status === 'completed') {
      acc[task.assigned_to_email].completed++;
    }
    return acc;
  }, {});

  const topPerformers = Object.values(staffPerformance)
    .map(p => ({
      ...p,
      rate: p.total > 0 ? Math.round((p.completed / p.total) * 100) : 0,
    }))
    .sort((a, b) => b.rate - a.rate)
    .slice(0, 10);

  const exportToCSV = () => {
    const csvData = [
      ['AURA Task Completion Report', `Generated: ${format(new Date(), 'PPP')}`],
      [''],
      ['Overall Stats'],
      ['Total Tasks', filteredTasks.length],
      ['Completed', filteredTasks.filter(t => t.status === 'completed').length],
      ['In Progress', filteredTasks.filter(t => t.status === 'in_progress').length],
      ['Pending', filteredTasks.filter(t => t.status === 'pending').length],
      ['Overdue', filteredTasks.filter(t => t.status === 'overdue').length],
      [''],
      ['Top Performers'],
      ['Name', 'Email', 'Completed', 'Total', 'Rate'],
      ...topPerformers.map(p => [p.name, p.email, p.completed, p.total, `${p.rate}%`]),
    ];

    const csvContent = csvData.map(row => row.join(',')).join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `task-report-${format(new Date(), 'yyyy-MM-dd')}.csv`;
    a.click();
  };

  return (
    <div className="p-6 md:p-8 bg-gray-50 min-h-screen">
      <div className="max-w-7xl mx-auto">
        {/* Back Buttons */}
        <div className="flex gap-3 mb-6">
          <Link to={createPageUrl("ManagerDashboard")}>
            <Button variant="outline" size="sm">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back
            </Button>
          </Link>
          <Link to={createPageUrl("Dashboard")}>
            <Button variant="outline" size="sm">
              <Home className="w-4 h-4 mr-2" />
              Dashboard
            </Button>
          </Link>
        </div>

        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-8">
          <div>
            <h1 className="text-3xl font-bold text-gray-900 mb-2">Task Completion Reports</h1>
            <p className="text-gray-600">Track task completion rates by role and department</p>
          </div>
          <div className="flex gap-3">
            <Select value={filterDepartment} onValueChange={setFilterDepartment}>
              <SelectTrigger className="w-40">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Departments</SelectItem>
                <SelectItem value="kitchen">Kitchen</SelectItem>
                <SelectItem value="front_of_house">Front of House</SelectItem>
                <SelectItem value="bar">Bar</SelectItem>
                <SelectItem value="management">Management</SelectItem>
                <SelectItem value="cleaning">Cleaning</SelectItem>
              </SelectContent>
            </Select>
            <Select value={timeRange} onValueChange={setTimeRange}>
              <SelectTrigger className="w-40">
                <Calendar className="w-4 h-4 mr-2" />
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="7days">Last 7 Days</SelectItem>
                <SelectItem value="30days">Last 30 Days</SelectItem>
                <SelectItem value="90days">Last 90 Days</SelectItem>
              </SelectContent>
            </Select>
            <Button variant="outline" onClick={exportToCSV}>
              <Download className="w-4 h-4 mr-2" />
              Export CSV
            </Button>
          </div>
        </div>

        {/* Quick Stats */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
          <Card>
            <CardContent className="p-4 text-center">
              <CheckCircle className="w-8 h-8 text-green-600 mx-auto mb-2" />
              <p className="text-3xl font-bold text-gray-900">
                {filteredTasks.filter(t => t.status === 'completed').length}
              </p>
              <p className="text-sm text-gray-600">Completed</p>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-4 text-center">
              <Clock className="w-8 h-8 text-blue-600 mx-auto mb-2" />
              <p className="text-3xl font-bold text-gray-900">
                {filteredTasks.filter(t => t.status === 'in_progress').length}
              </p>
              <p className="text-sm text-gray-600">In Progress</p>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-4 text-center">
              <AlertTriangle className="w-8 h-8 text-yellow-600 mx-auto mb-2" />
              <p className="text-3xl font-bold text-gray-900">
                {filteredTasks.filter(t => t.status === 'pending').length}
              </p>
              <p className="text-sm text-gray-600">Pending</p>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-4 text-center">
              <AlertCircle className="w-8 h-8 text-red-600 mx-auto mb-2" />
              <p className="text-3xl font-bold text-gray-900">
                {filteredTasks.filter(t => t.status === 'overdue').length}
              </p>
              <p className="text-sm text-gray-600">Overdue</p>
            </CardContent>
          </Card>
        </div>

        <div className="space-y-6">
          {/* Completion Trend */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <TrendingUp className="w-5 h-5 text-blue-600" />
                Completion Rate Trend
              </CardTitle>
            </CardHeader>
            <CardContent>
              <ResponsiveContainer width="100%" height={300}>
                <LineChart data={completionTrendData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                  <XAxis dataKey="date" tick={{ fill: '#64748b', fontSize: 12 }} />
                  <YAxis tick={{ fill: '#64748b', fontSize: 12 }} />
                  <Tooltip />
                  <Line type="monotone" dataKey="rate" stroke="#3b82f6" strokeWidth={2} />
                </LineChart>
              </ResponsiveContainer>
            </CardContent>
          </Card>

          <div className="grid md:grid-cols-2 gap-6">
            {/* Status Distribution */}
            <Card>
              <CardHeader>
                <CardTitle>Task Status Distribution</CardTitle>
              </CardHeader>
              <CardContent>
                <ResponsiveContainer width="100%" height={300}>
                  <PieChart>
                    <Pie
                      data={statusData}
                      cx="50%"
                      cy="50%"
                      labelLine={false}
                      label={({ name, percent }) => `${name}: ${(percent * 100).toFixed(0)}%`}
                      outerRadius={80}
                      fill="#8884d8"
                      dataKey="value"
                    >
                      {statusData.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={entry.color} />
                      ))}
                    </Pie>
                    <Tooltip />
                  </PieChart>
                </ResponsiveContainer>
              </CardContent>
            </Card>

            {/* Completion by Role */}
            <Card>
              <CardHeader>
                <CardTitle>Completion Rate by Role</CardTitle>
              </CardHeader>
              <CardContent>
                <ResponsiveContainer width="100%" height={300}>
                  <BarChart data={roleData}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                    <XAxis dataKey="role" tick={{ fill: '#64748b', fontSize: 10 }} />
                    <YAxis tick={{ fill: '#64748b', fontSize: 12 }} />
                    <Tooltip />
                    <Bar dataKey="rate" fill="#10b981" radius={[8, 8, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </CardContent>
            </Card>
          </div>

          {/* Top Performers */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Users className="w-5 h-5 text-green-600" />
                Top Performers
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {topPerformers.map((performer, index) => (
                  <div key={performer.email} className="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
                    <div className="flex items-center gap-3">
                      <div className={`w-8 h-8 rounded-full flex items-center justify-center text-white font-bold ${
                        index === 0 ? 'bg-yellow-500' :
                        index === 1 ? 'bg-gray-400' :
                        index === 2 ? 'bg-amber-600' :
                        'bg-blue-500'
                      }`}>
                        {index + 1}
                      </div>
                      <div>
                        <p className="font-medium text-gray-900">{performer.name}</p>
                        <p className="text-xs text-gray-500">{performer.email}</p>
                      </div>
                    </div>
                    <div className="text-right">
                      <p className="text-2xl font-bold text-green-600">{performer.rate}%</p>
                      <p className="text-xs text-gray-500">{performer.completed}/{performer.total} tasks</p>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
