/**
 * 🌉 BRIDGE EVENT EMITTER
 * Utility functions for modules to emit events to DataBridge
 * Use these helper functions instead of directly creating BridgeEventLog records
 */

import { base44 } from '@/api/base44Client';

export class BridgeEventEmitter {
  /**
   * Emit a new event to the DataBridge
   */
  static async emit(eventData) {
    try {
      const event = await base44.entities.BridgeEventLog.create({
        event_id: `evt_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
        source_module: eventData.source_module,
        event_type: eventData.event_type,
        reference_id: eventData.reference_id,
        reference_type: eventData.reference_type,
        payload: eventData.payload || {},
        target_modules: eventData.target_modules || [],
        status: 'pending',
        priority: eventData.priority || 'normal',
        triggered_by_user: eventData.user_email || 'system',
        triggered_by_name: eventData.user_name || 'System',
      });

      console.log(`[BridgeEmitter] Event emitted: ${eventData.event_type} from ${eventData.source_module}`);
      return event;
    } catch (error) {
      console.error('[BridgeEmitter] Failed to emit event:', error);
      throw error;
    }
  }

  // ==================== CONVENIENCE METHODS ====================

  static async taskCompleted(taskData, user) {
    return this.emit({
      source_module: 'tasks',
      event_type: 'task_completed',
      reference_id: taskData.id,
      reference_type: 'AutoGeneratedTask',
      payload: {
        task_id: taskData.id,
        task_name: taskData.task_name,
        task_type: taskData.task_type,
        assigned_to_email: taskData.assigned_to_email,
        assigned_to_name: taskData.assigned_to_name,
        venue_id: taskData.venue_id,
        shift_id: taskData.shift_id,
        completed_at: new Date().toISOString()
      },
      target_modules: ['leafe', 'compliance'],
      user_email: user?.email,
      user_name: user?.full_name
    });
  }

  static async checklistCompleted(checklistData, user) {
    return this.emit({
      source_module: 'checklists',
      event_type: 'checklist_completed',
      reference_id: checklistData.id,
      reference_type: 'ChecklistExecution',
      payload: {
        checklist_id: checklistData.id,
        checklist_name: checklistData.template_name,
        score: checklistData.progress || 0,
        completed_by_id: user?.id,
        completed_by_email: user?.email,
        completed_by_name: user?.full_name,
        shift_id: checklistData.shift_id,
        shift_date: checklistData.execution_date
      },
      target_modules: ['compliance', 'leafe'],
      priority: checklistData.progress < 70 ? 'high' : 'normal',
      user_email: user?.email,
      user_name: user?.full_name
    });
  }

  static async shiftStarted(shiftData, user) {
    return this.emit({
      source_module: 'workforce',
      event_type: 'shift_started',
      reference_id: shiftData.id,
      reference_type: 'Shift',
      payload: {
        shift_id: shiftData.id,
        staff_email: shiftData.staff_email,
        staff_name: shiftData.staff_name,
        venue_id: shiftData.venue_id,
        venue_name: shiftData.venue_name,
        shift_type: shiftData.shift_type,
        start_time: shiftData.start_time
      },
      target_modules: ['leafe', 'compliance'],
      user_email: user?.email,
      user_name: user?.full_name
    });
  }

  static async shiftEnded(shiftData, user) {
    return this.emit({
      source_module: 'workforce',
      event_type: 'shift_ended',
      reference_id: shiftData.id,
      reference_type: 'Shift',
      payload: {
        shift_id: shiftData.id,
        staff_email: shiftData.staff_email,
        staff_name: shiftData.staff_name,
        venue_id: shiftData.venue_id,
        venue_name: shiftData.venue_name,
        shift_type: shiftData.shift_type,
        end_time: shiftData.end_time
      },
      target_modules: ['leafe', 'compliance'],
      user_email: user?.email,
      user_name: user?.full_name
    });
  }

  static async stockReceived(orderData, user) {
    return this.emit({
      source_module: 'inventory',
      event_type: 'stock_received',
      reference_id: orderData.id,
      reference_type: 'PurchaseOrder',
      payload: {
        order_id: orderData.id,
        order_number: orderData.order_number,
        supplier_name: orderData.supplier_name,
        total: orderData.total,
        received_by: user?.email,
        received_by_name: user?.full_name,
        received_by_id: user?.id
      },
      target_modules: ['compliance'],
      user_email: user?.email,
      user_name: user?.full_name
    });
  }

  static async documentSigned(documentData, user) {
    return this.emit({
      source_module: 'documents',
      event_type: 'document_signed',
      reference_id: documentData.id,
      reference_type: 'DocumentReview',
      payload: {
        document_id: documentData.id,
        document_name: documentData.document_title,
        document_type: documentData.document_type,
        staff_email: user?.email,
        staff_name: user?.full_name,
        signed_at: new Date().toISOString()
      },
      target_modules: ['workforce', 'compliance'],
      user_email: user?.email,
      user_name: user?.full_name
    });
  }

  static async auditCompleted(auditData, user) {
    return this.emit({
      source_module: 'leafe',
      event_type: 'audit_completed',
      reference_id: auditData.id,
      reference_type: 'LeafeAuditRecord',
      payload: {
        audit_id: auditData.id,
        venue_id: auditData.venue_id,
        venue_name: auditData.venue_name,
        overall_score: auditData.overall_score,
        audit_type: auditData.audit_type,
        audit_date: auditData.audit_date
      },
      target_modules: ['compliance', 'leafe'],
      priority: auditData.overall_score < 70 ? 'high' : 'normal',
      user_email: user?.email,
      user_name: user?.full_name
    });
  }
}

export default BridgeEventEmitter;