/**
 * 📚 METADATA CONNECTION EXAMPLES
 * Real-world examples of how to use MetadataConnector in different scenarios
 */

import { MetadataConnector } from './MetadataConnector';
import { base44 } from '@/api/base44Client';

/**
 * EXAMPLE 1: Link Task to LeafeCore Checklist
 * When a task is created, link it to a kitchen checklist
 */
export async function linkTaskToChecklist(taskId, checklistId) {
  try {
    // Get task data
    const taskRecords = await base44.entities.AutoGeneratedTask.filter({ id: taskId });
    if (taskRecords.length === 0) return null;
    const task = taskRecords[0];

    // Create metadata link
    await MetadataConnector.createMetadataLink(
      'LeafeChecklistEntry',
      checklistId,
      'tasks',
      taskId,
      {
        task_name: task.task_name,
        task_type: task.task_type,
        priority: task.priority
      }
    );

    console.log('✅ Task linked to checklist via metadata');
    return true;
  } catch (error) {
    console.error('❌ Failed to link task to checklist:', error);
    return false;
  }
}

/**
 * EXAMPLE 2: Get all checklists linked to a shift
 * Retrieve checklists without joining tables
 */
export async function getChecklistsForShift(shiftId) {
  try {
    // Query by metadata link
    const checklists = await MetadataConnector.queryByMetadataLink(
      'LeafeChecklistEntry',
      'workforce',
      shiftId
    );

    console.log(`Found ${checklists.length} checklists for shift ${shiftId}`);
    return checklists;
  } catch (error) {
    console.error('Error fetching checklists for shift:', error);
    return [];
  }
}

/**
 * EXAMPLE 3: Resolve inventory order from compliance log
 * Get order details when viewing email log
 */
export async function getOrderFromEmailLog(emailLogId) {
  try {
    // Get email log
    const logs = await base44.entities.ComplianceEmailLog.filter({ id: emailLogId });
    if (logs.length === 0) return null;
    const log = logs[0];

    // Check if it has order metadata
    const orderLink = log.metadata?.inventory_link;
    if (!orderLink) return null;

    // Resolve the order reference
    const order = await MetadataConnector.resolveReference(
      'PurchaseOrder',
      orderLink.source_record_id,
      ['order_number', 'supplier_name', 'total', 'status']
    );

    console.log('✅ Resolved order from email log:', order);
    return order;
  } catch (error) {
    console.error('Error resolving order:', error);
    return null;
  }
}

/**
 * EXAMPLE 4: Batch resolve staff names for payroll report
 * Efficiently fetch staff data for multiple records
 */
export async function enrichPayrollWithStaffData(payrollRecords) {
  try {
    // Extract unique staff emails
    const staffEmails = [...new Set(payrollRecords.map(r => r.staff_email))];

    // Get all staff records in one query
    const allStaff = await base44.entities.User.list();
    const staffMap = {};
    
    allStaff.forEach(staff => {
      if (staffEmails.includes(staff.email)) {
        staffMap[staff.email] = {
          full_name: staff.full_name,
          position: staff.position,
          department: staff.department,
          photo_url: staff.photo_url
        };
      }
    });

    // Enrich payroll records with staff data (via metadata, not joins)
    const enriched = payrollRecords.map(record => ({
      ...record,
      staff_metadata: staffMap[record.staff_email] || null
    }));

    console.log(`✅ Enriched ${enriched.length} payroll records with staff metadata`);
    return enriched;
  } catch (error) {
    console.error('Error enriching payroll data:', error);
    return payrollRecords;
  }
}

/**
 * EXAMPLE 5: Link document signature to onboarding step
 * When staff signs document, unlock next onboarding step
 */
export async function linkDocumentToOnboarding(documentReviewId, onboardingStepId) {
  try {
    // Get document review
    const reviews = await base44.entities.DocumentReview.filter({ id: documentReviewId });
    if (reviews.length === 0) return false;
    const review = reviews[0];

    // Validate connection first
    const valid = await MetadataConnector.validateConnection(
      'DocumentReview',
      documentReviewId,
      'OnboardingProgress',
      onboardingStepId
    );

    if (!valid) {
      console.warn('Invalid connection - records not found');
      return false;
    }

    // Create metadata link
    await MetadataConnector.createMetadataLink(
      'OnboardingProgress',
      onboardingStepId,
      'documents',
      documentReviewId,
      {
        document_title: review.document_title,
        signed_at: review.acknowledgment_date,
        signature_url: review.signature_url
      }
    );

    console.log('✅ Document linked to onboarding step');
    return true;
  } catch (error) {
    console.error('Error linking document to onboarding:', error);
    return false;
  }
}

/**
 * EXAMPLE 6: Get hygiene score impact from completed checklist
 * Show which checklists contributed to venue score
 */
export async function getChecklistImpactOnScore(venueId) {
  try {
    // Get hygiene score record
    const scores = await base44.entities.LeafeHygieneScore.filter({ venue_id: venueId });
    if (scores.length === 0) return null;
    const score = scores[0];

    // Get all checklists for this venue
    const checklists = await base44.entities.LeafeChecklistEntry.filter({
      venue_id: venueId,
      status: 'completed'
    });

    // Calculate impact (metadata approach - no joins)
    const recentChecklists = checklists
      .filter(c => new Date(c.completion_date) >= new Date(Date.now() - 7 * 24 * 60 * 60 * 1000))
      .map(checklist => ({
        checklist_id: checklist.id,
        template_name: checklist.template_name,
        score: checklist.percentage,
        completion_date: checklist.completion_date,
        impact: checklist.percentage - score.score // Simple impact calculation
      }));

    console.log(`✅ Analyzed ${recentChecklists.length} checklists for score impact`);
    
    return {
      current_score: score.score,
      total_checklists: recentChecklists.length,
      checklists: recentChecklists
    };
  } catch (error) {
    console.error('Error calculating checklist impact:', error);
    return null;
  }
}

/**
 * EXAMPLE 7: Remove metadata link when record deleted
 * Clean up when source record is removed
 */
export async function cleanupDeletedTaskLinks(taskId) {
  try {
    // Find all checklists linked to this task
    const linkedChecklists = await MetadataConnector.queryByMetadataLink(
      'LeafeChecklistEntry',
      'tasks',
      taskId
    );

    // Remove metadata links
    for (const checklist of linkedChecklists) {
      await MetadataConnector.removeMetadataLink(
        'LeafeChecklistEntry',
        checklist.id,
        'tasks'
      );
    }

    console.log(`✅ Cleaned up ${linkedChecklists.length} metadata links for deleted task`);
    return linkedChecklists.length;
  } catch (error) {
    console.error('Error cleaning up task links:', error);
    return 0;
  }
}

export default {
  linkTaskToChecklist,
  getChecklistsForShift,
  getOrderFromEmailLog,
  enrichPayrollWithStaffData,
  linkDocumentToOnboarding,
  getChecklistImpactOnScore,
  cleanupDeletedTaskLinks,
};