import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { useQuery } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuTrigger,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuItem,
} from "@/components/ui/dropdown-menu";
import { Bell, CheckCircle, Clock, AlertCircle, Calendar, ListChecks } from "lucide-react";
import { format, formatDistanceToNow } from "date-fns";
import { Link } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { motion, AnimatePresence } from "framer-motion";

export default function NotificationBell() {
  const [isOpen, setIsOpen] = useState(false);

  const { data: user } = useQuery({
    queryKey: ['currentUser'],
    queryFn: () => base44.auth.me(),
  });

  // Get pending checklists
  const { data: myExecutions = [] } = useQuery({
    queryKey: ['myChecklistExecutions', user?.email],
    queryFn: async () => {
      if (!user?.email) return [];
      const allExecutions = await base44.entities.ChecklistExecution.list('-execution_date');
      return allExecutions.filter(exec => 
        exec.assigned_to_email === user.email && 
        exec.status !== 'completed'
      );
    },
    enabled: !!user?.email,
    refetchInterval: 30000, // Refetch every 30 seconds
  });

  // Get pending tasks
  const { data: myTasks = [] } = useQuery({
    queryKey: ['myPendingTasks', user?.email],
    queryFn: async () => {
      if (!user?.email) return [];
      const allTasks = await base44.entities.AutoGeneratedTask.list('-created_date');
      return allTasks.filter(task => 
        task.assigned_to_email === user.email && 
        (task.status === 'pending' || task.status === 'in_progress')
      );
    },
    enabled: !!user?.email,
    refetchInterval: 30000,
  });

  // Get today's shifts
  const today = new Date().toISOString().split('T')[0];
  const { data: todayShifts = [] } = useQuery({
    queryKey: ['todayShifts', user?.email, today],
    queryFn: async () => {
      if (!user?.email) return [];
      return await base44.entities.Shift.filter({
        staff_email: user.email,
        shift_date: today,
      });
    },
    enabled: !!user?.email,
    refetchInterval: 60000, // Refetch every minute
  });

  // Check for overdue items
  const now = new Date();
  now.setHours(0, 0, 0, 0);
  
  const overdueChecklists = myExecutions.filter(exec => {
    const execDate = new Date(exec.execution_date);
    execDate.setHours(0, 0, 0, 0);
    return execDate < now && exec.status !== 'completed';
  });

  const overdueTasks = myTasks.filter(task => {
    if (!task.shift_date) return false;
    const taskDate = new Date(task.shift_date);
    taskDate.setHours(0, 0, 0, 0);
    return taskDate < now && task.status !== 'completed';
  });

  // Active shift
  const activeShift = todayShifts.find(s => s.status === 'in_progress');
  const nextShift = !activeShift ? todayShifts.find(s => s.status === 'scheduled') : null;

  // Build notifications array
  const notifications = [];

  // Add overdue checklists
  overdueChecklists.forEach(exec => {
    notifications.push({
      id: `checklist-${exec.id}`,
      type: 'checklist',
      priority: 'urgent',
      icon: AlertCircle,
      title: `Overdue: ${exec.template_name}`,
      description: `Due ${format(new Date(exec.execution_date), 'MMM d')}`,
      time: exec.execution_date,
      url: createPageUrl(`ExecuteChecklist?id=${exec.id}`),
    });
  });

  // Add pending checklists (not overdue)
  myExecutions.filter(exec => !overdueChecklists.includes(exec)).forEach(exec => {
    const execDate = new Date(exec.execution_date);
    const isToday = execDate.toDateString() === now.toDateString();
    
    notifications.push({
      id: `checklist-${exec.id}`,
      type: 'checklist',
      priority: isToday ? 'high' : 'normal',
      icon: CheckCircle,
      title: exec.template_name,
      description: isToday ? 'Due today' : `Due ${format(execDate, 'MMM d')}`,
      time: exec.execution_date,
      url: createPageUrl(`ExecuteChecklist?id=${exec.id}`),
      progress: getProgress(exec),
    });
  });

  // Add overdue tasks
  overdueTasks.forEach(task => {
    notifications.push({
      id: `task-${task.id}`,
      type: 'task',
      priority: 'urgent',
      icon: AlertCircle,
      title: `Overdue: ${task.task_name}`,
      description: task.description || 'Complete this task',
      time: task.shift_date,
      url: createPageUrl('MyTasks'),
    });
  });

  // Add today's tasks
  myTasks.filter(task => !overdueTasks.includes(task)).forEach(task => {
    const taskDate = task.shift_date ? new Date(task.shift_date) : null;
    const isToday = taskDate?.toDateString() === now.toDateString();
    
    if (isToday || !taskDate) {
      notifications.push({
        id: `task-${task.id}`,
        type: 'task',
        priority: task.priority === 'high' ? 'high' : 'normal',
        icon: ListChecks,
        title: task.task_name,
        description: task.description || 'Pending task',
        time: task.created_date,
        url: createPageUrl('MyTasks'),
      });
    }
  });

  // Add shift notifications
  if (activeShift) {
    notifications.push({
      id: `shift-active`,
      type: 'shift',
      priority: 'info',
      icon: Clock,
      title: 'Currently Clocked In',
      description: `${activeShift.role} • Started ${activeShift.clock_in_time ? format(new Date(activeShift.clock_in_time), 'h:mm a') : activeShift.start_time}`,
      time: activeShift.clock_in_time || activeShift.created_date,
      url: createPageUrl('ClockInOut'),
    });
  } else if (nextShift) {
    notifications.push({
      id: `shift-next`,
      type: 'shift',
      priority: 'info',
      icon: Calendar,
      title: 'Upcoming Shift',
      description: `${nextShift.role} • ${nextShift.start_time} - ${nextShift.end_time}`,
      time: nextShift.created_date,
      url: createPageUrl('ClockInOut'),
    });
  }

  // Sort by priority and time
  const priorityOrder = { urgent: 0, high: 1, normal: 2, info: 3 };
  notifications.sort((a, b) => {
    if (a.priority !== b.priority) {
      return priorityOrder[a.priority] - priorityOrder[b.priority];
    }
    return new Date(b.time) - new Date(a.time);
  });

  const totalCount = notifications.length;
  const urgentCount = notifications.filter(n => n.priority === 'urgent').length;

  function getProgress(execution) {
    if (!execution.tasks || execution.tasks.length === 0) return 0;
    const completed = execution.tasks.filter(t => 
      ['pass', 'fail', 'na'].includes(t.status)
    ).length;
    return Math.round((completed / execution.tasks.length) * 100);
  }

  function getPriorityColor(priority) {
    switch (priority) {
      case 'urgent': return 'text-red-600 bg-red-50';
      case 'high': return 'text-orange-600 bg-orange-50';
      case 'info': return 'text-blue-600 bg-blue-50';
      default: return 'text-gray-600 bg-gray-50';
    }
  }

  return (
    <DropdownMenu open={isOpen} onOpenChange={setIsOpen}>
      <DropdownMenuTrigger asChild>
        <Button 
          variant="ghost" 
          size="icon" 
          className="relative hover:bg-slate-100 transition-colors"
        >
          <Bell className={`w-5 h-5 ${totalCount > 0 ? 'text-blue-600' : 'text-slate-600'}`} />
          <AnimatePresence>
            {totalCount > 0 && (
              <motion.div
                initial={{ scale: 0 }}
                animate={{ scale: 1 }}
                exit={{ scale: 0 }}
                className="absolute -top-1 -right-1"
              >
                <Badge 
                  className={`h-5 min-w-[20px] px-1 text-[10px] font-bold ${
                    urgentCount > 0 
                      ? 'bg-red-600 hover:bg-red-700' 
                      : 'bg-blue-600 hover:bg-blue-700'
                  }`}
                >
                  {totalCount > 99 ? '99+' : totalCount}
                </Badge>
              </motion.div>
            )}
          </AnimatePresence>
        </Button>
      </DropdownMenuTrigger>

      <DropdownMenuContent 
        align="end" 
        className="w-80 max-h-[500px] overflow-y-auto"
        sideOffset={8}
      >
        <DropdownMenuLabel className="flex items-center justify-between">
          <span className="font-bold text-base">Notifications</span>
          {totalCount > 0 && (
            <Badge variant="secondary" className="text-xs">
              {totalCount} {totalCount === 1 ? 'item' : 'items'}
            </Badge>
          )}
        </DropdownMenuLabel>
        <DropdownMenuSeparator />

        {notifications.length === 0 ? (
          <div className="p-8 text-center">
            <Bell className="w-12 h-12 text-gray-300 mx-auto mb-3" />
            <p className="text-sm text-gray-500 font-medium">No notifications</p>
            <p className="text-xs text-gray-400 mt-1">You're all caught up! 🎉</p>
          </div>
        ) : (
          <div className="py-2">
            {notifications.map((notification) => {
              const Icon = notification.icon;
              return (
                <Link 
                  key={notification.id} 
                  to={notification.url}
                  onClick={() => setIsOpen(false)}
                >
                  <DropdownMenuItem className="p-3 cursor-pointer hover:bg-slate-50 transition-colors">
                    <div className="flex gap-3 w-full">
                      <div className={`w-10 h-10 rounded-full flex items-center justify-center flex-shrink-0 ${getPriorityColor(notification.priority)}`}>
                        <Icon className="w-5 h-5" />
                      </div>
                      <div className="flex-1 min-w-0">
                        <p className="font-semibold text-sm text-gray-900 truncate mb-0.5">
                          {notification.title}
                        </p>
                        <p className="text-xs text-gray-600 truncate mb-1">
                          {notification.description}
                        </p>
                        {notification.progress !== undefined && (
                          <div className="flex items-center gap-2 mb-1">
                            <div className="flex-1 h-1.5 bg-gray-200 rounded-full overflow-hidden">
                              <div 
                                className="h-full bg-blue-600 rounded-full transition-all"
                                style={{ width: `${notification.progress}%` }}
                              />
                            </div>
                            <span className="text-[10px] text-gray-500 font-medium">
                              {notification.progress}%
                            </span>
                          </div>
                        )}
                        <p className="text-[10px] text-gray-400">
                          {formatDistanceToNow(new Date(notification.time), { addSuffix: true })}
                        </p>
                      </div>
                    </div>
                  </DropdownMenuItem>
                </Link>
              );
            })}
          </div>
        )}

        {notifications.length > 0 && (
          <>
            <DropdownMenuSeparator />
            <div className="p-2">
              <Link to={createPageUrl('MyTasks')} onClick={() => setIsOpen(false)}>
                <Button variant="ghost" className="w-full text-xs">
                  View All Tasks
                </Button>
              </Link>
            </div>
          </>
        )}
      </DropdownMenuContent>
    </DropdownMenu>
  );
}