import React from "react";
import { base44 } from "@/api/base44Client";
import { useQuery } from "@tanstack/react-query";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { AlertTriangle, CheckCircle, AlertCircle, TrendingUp } from "lucide-react";
import { Link } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { motion } from "framer-motion";

export default function SmartAlerts() {
  const { data: user } = useQuery({
    queryKey: ['currentUser'],
    queryFn: () => base44.auth.me(),
  });

  const isManager = user?.position === 'manager' || user?.position === 'owner' || user?.role === 'admin';

  // Fetch overdue tasks
  const { data: allTasks = [] } = useQuery({
    queryKey: ['allTasksForAlerts'],
    queryFn: () => base44.entities.AutoGeneratedTask.list('-shift_date'),
    enabled: isManager,
  });

  // Fetch responsibilities
  const { data: responsibilities = [] } = useQuery({
    queryKey: ['responsibilities'],
    queryFn: () => base44.entities.RoleResponsibility.list(),
    enabled: isManager,
  });

  // Fetch all shifts
  const { data: shifts = [] } = useQuery({
    queryKey: ['shiftsForAlerts'],
    queryFn: () => base44.entities.Shift.list('-shift_date', 100),
    enabled: isManager,
  });

  if (!isManager) return null;

  const yesterday = new Date();
  yesterday.setDate(yesterday.getDate() - 1);
  const yesterdayStr = yesterday.toISOString().split('T')[0];

  const overdueTasks = allTasks.filter(t => 
    t.shift_date === yesterdayStr && t.status !== 'completed'
  );

  // Calculate completion rates by department
  const today = new Date().toISOString().split('T')[0];
  const todayTasks = allTasks.filter(t => t.shift_date === today);
  
  const departmentStats = todayTasks.reduce((acc, task) => {
    if (!acc[task.department]) {
      acc[task.department] = { total: 0, completed: 0 };
    }
    acc[task.department].total++;
    if (task.status === 'completed') {
      acc[task.department].completed++;
    }
    return acc;
  }, {});

  // Find roles without responsibilities
  const allRoles = [...new Set(shifts.map(s => s.role))];
  const rolesWithoutResponsibilities = allRoles.filter(role => 
    !responsibilities.some(r => r.position === role && r.is_active)
  );

  const alerts = [];

  // Overdue tasks alert
  if (overdueTasks.length > 0) {
    alerts.push({
      type: 'warning',
      icon: AlertTriangle,
      title: `${overdueTasks.length} tasks overdue from yesterday's shift`,
      description: 'Review incomplete tasks and follow up with staff',
      action: 'View Tasks',
      link: createPageUrl('ManagerDashboard'),
      color: 'orange'
    });
  }

  // Department completion alerts
  Object.entries(departmentStats).forEach(([dept, stats]) => {
    const percentage = Math.round((stats.completed / stats.total) * 100);
    if (percentage >= 90) {
      alerts.push({
        type: 'success',
        icon: CheckCircle,
        title: `${dept.replace('_', ' ')} tasks ${percentage}% complete`,
        description: `${stats.completed} of ${stats.total} tasks done`,
        action: 'View Details',
        link: createPageUrl('Reports'),
        color: 'green'
      });
    } else if (percentage < 50 && stats.total > 3) {
      alerts.push({
        type: 'warning',
        icon: AlertCircle,
        title: `${dept.replace('_', ' ')} tasks only ${percentage}% complete`,
        description: `${stats.total - stats.completed} tasks still pending`,
        action: 'Check Status',
        link: createPageUrl('ManagerDashboard'),
        color: 'red'
      });
    }
  });

  // Missing responsibilities alert
  if (rolesWithoutResponsibilities.length > 0) {
    alerts.push({
      type: 'info',
      icon: AlertCircle,
      title: `No responsibilities assigned to ${rolesWithoutResponsibilities.length} role(s)`,
      description: `Roles: ${rolesWithoutResponsibilities.join(', ')} — Review matrix`,
      action: 'Configure',
      link: createPageUrl('ManagerDashboard') + '?tab=responsibilities',
      color: 'blue'
    });
  }

  if (alerts.length === 0) return null;

  return (
    <div className="space-y-3 mb-6">
      {alerts.map((alert, index) => (
        <motion.div
          key={index}
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: index * 0.1 }}
        >
          <Card className={`border-l-4 border-l-${alert.color}-500 bg-${alert.color}-50`}>
            <CardContent className="p-4">
              <div className="flex items-start justify-between gap-4">
                <div className="flex items-start gap-3 flex-1">
                  <div className={`p-2 bg-${alert.color}-100 rounded-lg`}>
                    <alert.icon className={`w-5 h-5 text-${alert.color}-600`} />
                  </div>
                  <div className="flex-1">
                    <h4 className={`font-semibold text-${alert.color}-900 mb-1`}>
                      {alert.title}
                    </h4>
                    <p className={`text-sm text-${alert.color}-700`}>
                      {alert.description}
                    </p>
                  </div>
                </div>
                <Link to={alert.link}>
                  <Button size="sm" variant="outline" className="whitespace-nowrap">
                    {alert.action}
                  </Button>
                </Link>
              </div>
            </CardContent>
          </Card>
        </motion.div>
      ))}
    </div>
  );
}