import { useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { useQuery } from "@tanstack/react-query";

/**
 * Background component that automatically generates tasks when shifts are created
 * Runs silently in the background - no UI rendering
 */
export default function TaskAutomationEngine() {
  const { data: shifts = [] } = useQuery({
    queryKey: ['allShifts'],
    queryFn: () => base44.entities.Shift.list('-shift_date'),
    refetchInterval: 60000, // Check every minute
  });

  const { data: responsibilities = [] } = useQuery({
    queryKey: ['responsibilities'],
    queryFn: () => base44.entities.RoleResponsibility.list(),
  });

  const { data: existingTasks = [] } = useQuery({
    queryKey: ['autoGeneratedTasks'],
    queryFn: () => base44.entities.AutoGeneratedTask.list(),
  });

  useEffect(() => {
    if (shifts.length === 0 || responsibilities.length === 0) return;

    const generateTasksForShifts = async () => {
      for (const shift of shifts) {
        // Only process scheduled or in_progress shifts
        if (shift.status !== 'scheduled' && shift.status !== 'in_progress') continue;

        // Check if tasks already generated for this shift
        const tasksExist = existingTasks.some(t => t.shift_id === shift.id);
        if (tasksExist) continue;

        // Find matching responsibility
        const roleResponsibility = responsibilities.find(
          r => r.position === shift.role && r.is_active && r.auto_assign_enabled
        );

        if (!roleResponsibility) continue;

        const shiftDate = new Date(shift.shift_date);
        const dayOfWeek = shiftDate.toLocaleDateString('en-US', { weekday: 'lowercase' });
        const dayOfMonth = shiftDate.getDate();

        const tasksToCreate = [];

        // Generate daily tasks
        if (roleResponsibility.daily_tasks && Array.isArray(roleResponsibility.daily_tasks)) {
          for (const task of roleResponsibility.daily_tasks) {
            if (typeof task === 'string') {
              // Old format - simple string
              tasksToCreate.push({
                task_name: task,
                description: task,
                task_type: 'daily',
                priority: 'medium',
                estimated_minutes: 30,
              });
            } else if (typeof task === 'object') {
              // New format - structured object
              tasksToCreate.push({
                task_name: task.task_name || task.description || 'Unnamed Task',
                description: task.description || task.task_name || '',
                task_type: 'daily',
                priority: task.priority || 'medium',
                estimated_minutes: task.estimated_minutes || 30,
                requires_photo: task.requires_photo || false,
                linked_form_id: task.linked_form_id || null,
              });
            }
          }
        }

        // Generate weekly tasks (only on matching day)
        if (roleResponsibility.weekly_tasks && Array.isArray(roleResponsibility.weekly_tasks)) {
          for (const task of roleResponsibility.weekly_tasks) {
            if (typeof task === 'object' && task.day_of_week === dayOfWeek) {
              tasksToCreate.push({
                task_name: task.task_name || 'Unnamed Weekly Task',
                description: task.description || '',
                task_type: 'weekly',
                priority: task.priority || 'medium',
                estimated_minutes: task.estimated_minutes || 60,
                requires_photo: task.requires_photo || false,
                linked_form_id: task.linked_form_id || null,
              });
            }
          }
        }

        // Generate monthly tasks (only on matching day)
        if (roleResponsibility.monthly_tasks && Array.isArray(roleResponsibility.monthly_tasks)) {
          for (const task of roleResponsibility.monthly_tasks) {
            if (typeof task === 'object' && task.day_of_month === dayOfMonth) {
              tasksToCreate.push({
                task_name: task.task_name || 'Unnamed Monthly Task',
                description: task.description || '',
                task_type: 'monthly',
                priority: task.priority || 'high',
                estimated_minutes: task.estimated_minutes || 120,
                requires_photo: task.requires_photo || false,
                linked_form_id: task.linked_form_id || null,
              });
            }
          }
        }

        // Calculate due times based on shift end time
        const [endHour, endMin] = shift.end_time.split(':').map(Number);
        const shiftEndMinutes = endHour * 60 + endMin;

        // Create all tasks
        for (const taskData of tasksToCreate) {
          const dueMinutes = shiftEndMinutes - 30; // Due 30 mins before shift end
          const dueHour = Math.floor(dueMinutes / 60);
          const dueMin = dueMinutes % 60;

          try {
            await base44.entities.AutoGeneratedTask.create({
              ...taskData,
              assigned_to_email: shift.staff_email,
              assigned_to_name: shift.staff_name,
              role: shift.role,
              department: roleResponsibility.department,
              shift_id: shift.id,
              shift_date: shift.shift_date,
              linked_responsibility_id: roleResponsibility.id,
              due_time: `${String(dueHour).padStart(2, '0')}:${String(dueMin).padStart(2, '0')}`,
              status: 'pending',
              created_automatically: true,
            });
          } catch (error) {
            console.error('Error creating task:', error);
          }
        }
      }
    };

    generateTasksForShifts();
  }, [shifts, responsibilities, existingTasks]);

  return null; // No UI rendering
}