import { useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { useQuery } from "@tanstack/react-query";

/**
 * Background component that automatically generates tasks when shifts are created
 * Also sends notifications for task events
 */
export default function TaskAutomationEngine() {
  const { data: shifts = [] } = useQuery({
    queryKey: ['allShifts'],
    queryFn: () => base44.entities.Shift.list('-shift_date'),
    refetchInterval: 60000,
  });

  const { data: responsibilities = [] } = useQuery({
    queryKey: ['responsibilities'],
    queryFn: () => base44.entities.RoleResponsibility.list(),
  });

  const { data: existingTasks = [] } = useQuery({
    queryKey: ['autoGeneratedTasks'],
    queryFn: () => base44.entities.AutoGeneratedTask.list(),
  });

  const { data: allTasks = [] } = useQuery({
    queryKey: ['allTasksForNotifications'],
    queryFn: () => base44.entities.AutoGeneratedTask.list('-created_date', 100),
    refetchInterval: 300000, // Check every 5 minutes
  });

  // Send notification helper
  const sendNotification = async (notificationData) => {
    try {
      await base44.entities.TaskNotification.create({
        ...notificationData,
        created_date: new Date().toISOString(),
      });
    } catch (error) {
      console.error('Error sending notification:', error);
    }
  };

  // Check for overdue tasks
  useEffect(() => {
    const checkOverdueTasks = async () => {
      const now = new Date();
      const today = now.toISOString().split('T')[0];
      const currentTime = `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`;

      for (const task of allTasks) {
        if (task.status === 'overdue') continue; // Already marked
        
        if (task.shift_date < today || (task.shift_date === today && task.due_time < currentTime)) {
          if (task.status !== 'completed') {
            // Mark as overdue
            await base44.entities.AutoGeneratedTask.update(task.id, {
              status: 'overdue'
            });

            // Notify manager
            await sendNotification({
              notification_type: 'task_overdue',
              recipient_email: task.assigned_to_email, // Notify staff first
              recipient_name: task.assigned_to_name,
              title: '⚠️ Task Overdue',
              message: `Task "${task.task_name}" is overdue from ${task.shift_date}`,
              related_task_id: task.id,
              priority: 'warning',
              action_url: '/pages/MyTasks',
            });
          }
        }
      }
    };

    checkOverdueTasks();
  }, [allTasks]);

  // Generate tasks for shifts
  useEffect(() => {
    if (shifts.length === 0 || responsibilities.length === 0) return;

    const generateTasksForShifts = async () => {
      for (const shift of shifts) {
        if (shift.status !== 'scheduled' && shift.status !== 'in_progress') continue;

        const tasksExist = existingTasks.some(t => t.shift_id === shift.id);
        if (tasksExist) continue;

        const roleResponsibility = responsibilities.find(
          r => r.position === shift.role && r.is_active && r.auto_assign_enabled
        );

        if (!roleResponsibility) {
          // Send notification about missing responsibilities
          await sendNotification({
            notification_type: 'no_responsibilities',
            recipient_email: shift.staff_email,
            recipient_name: shift.staff_name,
            title: '📋 No Tasks Assigned',
            message: `No responsibilities defined for role: ${shift.role}. Contact your manager.`,
            related_shift_id: shift.id,
            priority: 'info',
          });
          continue;
        }

        const shiftDate = new Date(shift.shift_date);
        const dayOfWeek = shiftDate.toLocaleDateString('en-US', { weekday: 'lowercase' });
        const dayOfMonth = shiftDate.getDate();

        const tasksToCreate = [];

        // Generate daily tasks
        if (roleResponsibility.daily_tasks && Array.isArray(roleResponsibility.daily_tasks)) {
          for (const task of roleResponsibility.daily_tasks) {
            if (typeof task === 'string') {
              tasksToCreate.push({
                task_name: task,
                description: task,
                task_type: 'daily',
                priority: 'medium',
                estimated_minutes: 30,
              });
            } else if (typeof task === 'object') {
              tasksToCreate.push({
                task_name: task.task_name || task.description || 'Unnamed Task',
                description: task.description || task.task_name || '',
                task_type: 'daily',
                priority: task.priority || 'medium',
                estimated_minutes: task.estimated_minutes || 30,
                requires_photo: task.requires_photo || false,
                linked_form_id: task.linked_form_id || null,
              });
            }
          }
        }

        // Generate weekly tasks
        if (roleResponsibility.weekly_tasks && Array.isArray(roleResponsibility.weekly_tasks)) {
          for (const task of roleResponsibility.weekly_tasks) {
            if (typeof task === 'object' && task.day_of_week === dayOfWeek) {
              tasksToCreate.push({
                task_name: task.task_name || 'Unnamed Weekly Task',
                description: task.description || '',
                task_type: 'weekly',
                priority: task.priority || 'medium',
                estimated_minutes: task.estimated_minutes || 60,
                requires_photo: task.requires_photo || false,
                linked_form_id: task.linked_form_id || null,
              });
            }
          }
        }

        // Generate monthly tasks
        if (roleResponsibility.monthly_tasks && Array.isArray(roleResponsibility.monthly_tasks)) {
          for (const task of roleResponsibility.monthly_tasks) {
            if (typeof task === 'object' && task.day_of_month === dayOfMonth) {
              tasksToCreate.push({
                task_name: task.task_name || 'Unnamed Monthly Task',
                description: task.description || '',
                task_type: 'monthly',
                priority: task.priority || 'high',
                estimated_minutes: task.estimated_minutes || 120,
                requires_photo: task.requires_photo || false,
                linked_form_id: task.linked_form_id || null,
              });
            }
          }
        }

        const [endHour, endMin] = shift.end_time.split(':').map(Number);
        const shiftEndMinutes = endHour * 60 + endMin;

        let tasksCreated = 0;
        for (const taskData of tasksToCreate) {
          const dueMinutes = shiftEndMinutes - 30;
          const dueHour = Math.floor(dueMinutes / 60);
          const dueMin = dueMinutes % 60;

          try {
            await base44.entities.AutoGeneratedTask.create({
              ...taskData,
              assigned_to_email: shift.staff_email,
              assigned_to_name: shift.staff_name,
              role: shift.role,
              department: roleResponsibility.department,
              shift_id: shift.id,
              shift_date: shift.shift_date,
              linked_responsibility_id: roleResponsibility.id,
              due_time: `${String(dueHour).padStart(2, '0')}:${String(dueMin).padStart(2, '0')}`,
              status: 'pending',
              created_automatically: true,
            });
            tasksCreated++;
          } catch (error) {
            console.error('Error creating task:', error);
          }
        }

        // Notify staff that tasks are ready
        if (tasksCreated > 0) {
          await sendNotification({
            notification_type: 'shift_tasks_ready',
            recipient_email: shift.staff_email,
            recipient_name: shift.staff_name,
            title: '📋 Your Shift Tasks Are Ready',
            message: `You have ${tasksCreated} tasks assigned for your shift on ${shift.shift_date}`,
            related_shift_id: shift.id,
            priority: 'info',
            action_url: '/pages/MyTasks',
          });
        }
      }
    };

    generateTasksForShifts();
  }, [shifts, responsibilities, existingTasks]);

  return null;
}