import React, { useEffect } from 'react';
import { base44 } from '@/api/base44Client';
import { useQueryClient } from '@tanstack/react-query';

/**
 * AURA Brain - Inventory Agent
 * Monitors stock levels and predicts shortages
 * Auto-creates purchase order drafts when needed
 */
export default function InventoryAgent() {
  const queryClient = useQueryClient();

  useEffect(() => {
    const runAgent = async () => {
      try {
        // Check if agent is enabled
        const configs = await base44.entities.AgentConfig.filter({ agent_name: 'inventory_agent' });
        const config = configs[0];
        
        if (!config || !config.is_enabled) {
          console.log('[InventoryAgent] Agent is disabled');
          return;
        }

        // 1️⃣ Find low stock items
        const ingredients = await base44.entities.Ingredient.list();
        const lowStockItems = ingredients.filter(ing => 
          ing.auto_order_enabled && 
          ing.supplier_id &&
          ing.current_stock <= (ing.reorder_point || 0)
        );

        if (lowStockItems.length === 0) {
          console.log('[InventoryAgent] No low stock items detected');
          return;
        }

        // 2️⃣ Group by supplier
        const supplierGroups = {};
        for (const item of lowStockItems) {
          if (!supplierGroups[item.supplier_id]) {
            supplierGroups[item.supplier_id] = [];
          }
          supplierGroups[item.supplier_id].push(item);
        }

        // 3️⃣ Create purchase order drafts
        for (const [supplierId, items] of Object.entries(supplierGroups)) {
          const firstItem = items[0];
          const supplier = await base44.entities.Supplier.filter({ id: supplierId });
          
          if (!supplier || supplier.length === 0) continue;
          
          const supplierData = supplier[0];
          
          // Calculate order items
          const orderItems = items.map(ing => {
            const quantityToOrder = ing.auto_order_quantity || 
              (ing.par_level ? ing.par_level - ing.current_stock : 10);
            
            return {
              ingredient_id: ing.id,
              ingredient_name: ing.name,
              quantity_ordered: quantityToOrder,
              quantity_received: 0,
              unit: ing.unit,
              unit_cost: ing.unit_cost,
              line_total: quantityToOrder * ing.unit_cost,
            };
          });

          const subtotal = orderItems.reduce((sum, item) => sum + item.line_total, 0);
          const tax = subtotal * 0.2;
          const total = subtotal + tax;

          // Create draft PO
          const orderNumber = `PO-${Date.now()}-${supplierId.slice(0, 4)}`;
          
          const purchaseOrder = await base44.entities.PurchaseOrder.create({
            order_number: orderNumber,
            supplier_id: supplierId,
            supplier_name: supplierData.name,
            supplier_email: supplierData.email,
            status: 'draft',
            items: orderItems,
            subtotal,
            tax,
            total,
            order_date: new Date().toISOString(),
            notes: '🤖 Auto-generated by AURA Inventory Agent',
          });

          // Log the action
          await base44.entities.AgentLog.create({
            agent_name: 'inventory_agent',
            action_type: 'order_suggested',
            action_description: `Created draft order for ${supplierData.name} - ${items.length} low stock items`,
            trigger_event: 'low_stock_detected',
            related_entity: 'PurchaseOrder',
            related_entity_id: purchaseOrder.id,
            related_entity_name: orderNumber,
            created_order_id: purchaseOrder.id,
            decision_reasoning: `${items.length} ingredients below reorder point. Total value: £${total.toFixed(2)}`,
            confidence_score: 0.95,
            severity: 'medium',
            status: 'pending',
            notification_sent: true,
            notification_recipients: ['manager@restaurant.com'],
            success: true,
            decision_data: {
              supplier_name: supplierData.name,
              items_count: items.length,
              total_cost: total,
              low_stock_items: items.map(i => i.name),
            },
          });

          // Create notification event
          await base44.entities.Event.create({
            source_module: 'ai',
            event_type: 'stock_low',
            title: '📦 Purchase Order Draft Created',
            message: `AURA detected ${items.length} low stock items from ${supplierData.name}. Draft order PO-${orderNumber} created for manager review (£${total.toFixed(2)})`,
            severity: 'warning',
            recipient_roles: ['manager', 'owner'],
            linked_entity_type: 'PurchaseOrder',
            linked_entity_id: purchaseOrder.id,
            linked_entity_name: orderNumber,
            action_url: '/ordering',
          });
        }

        console.log(`[InventoryAgent] Created ${Object.keys(supplierGroups).length} draft purchase orders`);

      } catch (error) {
        console.error('[InventoryAgent] Error:', error);
        
        try {
          await base44.entities.AgentLog.create({
            agent_name: 'inventory_agent',
            action_type: 'analysis',
            action_description: 'Agent run failed',
            trigger_event: 'scheduled_run',
            status: 'failed',
            success: false,
            error_message: error.message,
          });
        } catch (logError) {
          console.error('[InventoryAgent] Failed to log error:', logError);
        }
      }
    };

    // Run on mount
    runAgent();

    // Run every hour
    const interval = setInterval(runAgent, 60 * 60 * 1000);

    return () => clearInterval(interval);
  }, [queryClient]);

  return null;
}