/**
 * InventoryAgent - Autonomous Inventory Monitoring & Order Management
 * Monitors stock levels, auto-generates orders, predicts shortages
 */

import { base44 } from '@/api/base44Client';
import EventBus, { EVENT_TYPES } from './EventBus';

export class InventoryAgent {
  constructor() {
    this.name = 'inventory_agent';
    this.isRunning = false;
    this.lastRun = null;
  }

  /**
   * Check for low stock items
   */
  async checkLowStock() {
    try {
      const ingredients = await base44.entities.Ingredient.list('-current_stock', 100);
      
      const lowStockItems = ingredients.filter(ing => 
        ing.current_stock <= (ing.reorder_point || 0) && ing.supplier_id
      );

      let detected = 0;

      for (const item of lowStockItems) {
        await EventBus.emit(
          item.current_stock === 0 ? EVENT_TYPES.STOCK_CRITICAL : EVENT_TYPES.STOCK_LOW,
          {
            ingredient_id: item.id,
            ingredient_name: item.name,
            current_stock: item.current_stock,
            reorder_point: item.reorder_point,
            supplier_id: item.supplier_id
          }
        );

        detected++;
      }

      console.log(`📦 InventoryAgent: Detected ${detected} low stock items`);
      return { detected, lowStockItems };

    } catch (error) {
      console.warn('InventoryAgent: Error in checkLowStock:', error);
      return { detected: 0, error: error.message };
    }
  }

  /**
   * Auto-generate purchase orders for critical stock
   */
  async autoGenerateOrders() {
    try {
      const ingredients = await base44.entities.Ingredient.list('-current_stock', 100);
      
      const criticalItems = ingredients.filter(ing => 
        ing.auto_order_enabled &&
        ing.current_stock <= (ing.reorder_point || 0) * 0.3 &&
        ing.supplier_id
      );

      const ordersBySupplier = {};

      criticalItems.forEach(item => {
        if (!ordersBySupplier[item.supplier_id]) {
          ordersBySupplier[item.supplier_id] = {
            supplier_id: item.supplier_id,
            supplier_name: item.supplier_name,
            supplier_email: item.supplier_email,
            items: []
          };
        }

        const quantityToOrder = item.auto_order_quantity || 
          (item.par_level ? item.par_level - item.current_stock : 10);

        ordersBySupplier[item.supplier_id].items.push({
          ingredient_id: item.id,
          ingredient_name: item.name,
          quantity_ordered: quantityToOrder,
          unit: item.unit,
          unit_cost: item.unit_cost,
          line_total: parseFloat((quantityToOrder * item.unit_cost).toFixed(2))
        });
      });

      let generated = 0;

      for (const order of Object.values(ordersBySupplier)) {
        const subtotal = order.items.reduce((sum, item) => sum + item.line_total, 0);
        const taxRate = 0.20;
        const tax = subtotal * taxRate;
        const total = subtotal + tax;

        await base44.entities.PurchaseOrder.create({
          order_number: `PO-AUTO-${Date.now()}-${order.supplier_id.substring(0, 4)}`,
          supplier_id: order.supplier_id,
          supplier_name: order.supplier_name,
          supplier_email: order.supplier_email,
          status: 'draft',
          items: order.items,
          subtotal: parseFloat(subtotal.toFixed(2)),
          tax: parseFloat(tax.toFixed(2)),
          total: parseFloat(total.toFixed(2)),
          order_date: new Date().toISOString().split('T')[0],
          notes: 'AUTO-GENERATED by AURA Brain - Critical stock replenishment',
          auto_generated: true
        });

        await EventBus.emit(EVENT_TYPES.ORDER_GENERATED, {
          supplier_id: order.supplier_id,
          supplier_name: order.supplier_name,
          itemCount: order.items.length,
          total: total
        });

        generated++;
      }

      console.log(`🛒 InventoryAgent: Generated ${generated} draft orders`);
      return { generated };

    } catch (error) {
      console.warn('InventoryAgent: Error in autoGenerateOrders:', error);
      return { generated: 0, error: error.message };
    }
  }

  /**
   * Predict future shortages using historical data
   */
  async predictShortages() {
    try {
      const ingredients = await base44.entities.Ingredient.list('-current_stock', 100);
      
      const predictions = [];
      let created = 0;

      for (const item of ingredients) {
        if (item.current_stock > 0 && 
            item.current_stock < (item.reorder_point || 0) * 0.5 &&
            item.supplier_id) {
          
          const daysUntilOut = Math.ceil(item.current_stock / (item.reorder_point / 7));
          
          predictions.push({
            ingredient_id: item.id,
            ingredient_name: item.name,
            current_stock: item.current_stock,
            predicted_out_date: new Date(Date.now() + daysUntilOut * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
            confidence: 0.7
          });

          await base44.entities.AIPrediction.create({
            prediction_date: new Date().toISOString().split('T')[0],
            prediction_type: 'stock_shortage',
            target_date: new Date(Date.now() + daysUntilOut * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
            category: 'inventory',
            prediction_summary: `${item.name} predicted to run out in ${daysUntilOut} days`,
            confidence_level: 0.7,
            severity: daysUntilOut <= 3 ? 'high' : 'medium',
            recommended_actions: [
              `Order ${item.auto_order_quantity || item.par_level || 10} ${item.unit} from ${item.supplier_name}`,
              'Monitor usage closely',
              'Consider increasing par level'
            ],
            data_points_used: 1,
            pattern_detected: 'declining_stock_trend'
          });

          created++;
        }
      }

      console.log(`🔮 InventoryAgent: Created ${created} shortage predictions`);
      return { created, predictions };

    } catch (error) {
      console.warn('InventoryAgent: Error in predictShortages:', error);
      return { created: 0, error: error.message };
    }
  }
}